"use strict";		
var trans_items = {		
"Master Ball"	: 	"マスターボール",
"Ultra Ball"	: 	"ハイパーボール",
"Great Ball"	: 	"スーパーボール",
"Poké Ball"	: 	"モンスターボール",
"Safari Ball"	: 	"サファリボール",
"Net Ball"	: 	"ネットボール",
"Dive Ball"	: 	"ダイブボール",
"Nest Ball"	: 	"ネストボール",
"Repeat Ball"	: 	"リピートボール",
"Timer Ball"	: 	"タイマーボール",
"Luxury Ball"	: 	"ゴージャスボール",
"Premier Ball"	: 	"プレミアボール",
"Dusk Ball"	: 	"ダークボール",
"Heal Ball"	: 	"ヒールボール",
"Quick Ball"	: 	"クイックボール",
"Cherish Ball"	: 	"プレシャスボール",
"Potion"	: 	"キズぐすり",
"Antidote"	: 	"どくけし",
"Burn Heal"	: 	"やけどなおし",
"Ice Heal"	: 	"こおりなおし",
"Awakening"	: 	"ねむけざまし",
"Paralyze Heal"	: 	"まひなおし",
"Full Restore"	: 	"かいふくのくすり",
"Max Potion"	: 	"まんたんのくすり",
"Hyper Potion"	: 	"すごいキズぐすり",
"Super Potion"	: 	"いいキズぐすり",
"Full Heal"	: 	"なんでもなおし",
"Revive"	: 	"げんきのかけら",
"Max Revive"	: 	"げんきのかたまり",
"Fresh Water"	: 	"おいしいみず",
"Soda Pop"	: 	"サイコソーダ",
"Lemonade"	: 	"ミックスオレ",
"Moomoo Milk"	: 	"モーモーミルク",
"Energy Powder"	: 	"ちからのこな",
"Energy Root"	: 	"ちからのねっこ",
"Heal Powder"	: 	"ばんのうごな",
"Revival Herb"	: 	"ふっかつそう",
"Ether"	: 	"ピーピーエイド",
"Max Ether"	: 	"ピーピーリカバー",
"Elixir"	: 	"ピーピーエイダー",
"Max Elixir"	: 	"ピーピーマックス",
"Lava Cookie"	: 	"フエンせんべい",
"Berry Juice"	: 	"きのみジュース",
"Sacred Ash"	: 	"せいなるはい",
"HP Up"	: 	"マックスアップ",
"Protein"	: 	"タウリン",
"Iron"	: 	"ブロムヘキシン",
"Carbos"	: 	"インドメタシン",
"Calcium"	: 	"リゾチウム",
"Rare Candy"	: 	"ふしぎなアメ",
"PP Up"	: 	"ポイントアップ",
"Zinc"	: 	"キトサン",
"PP Max"	: 	"ポイントマックス",
"Old Gateau"	: 	"もりのヨウカン",
"Guard Spec."	: 	"エフェクトガード",
"Dire Hit"	: 	"クリティカット",
"X Attack"	: 	"プラスパワー",
"X Defense"	: 	"ディフェンダー",
"X Speed"	: 	"スピーダー",
"X Accuracy"	: 	"ヨクアタール",
"X Sp. Atk"	: 	"スペシャルアップ",
"X Sp. Def"	: 	"スペシャルガード",
"Poké Doll"	: 	"ピッピにんぎょう",
"Fluffy Tail"	: 	"エネコのシッポ",
"Blue Flute"	: 	"あおいビードロ",
"Yellow Flute"	: 	"きいろビードロ",
"Red Flute"	: 	"あかいビードロ",
"Black Flute"	: 	"くろいビードロ",
"White Flute"	: 	"しろいビードロ",
"Shoal Salt"	: 	"あさせのしお",
"Shoal Shell"	: 	"あさせのかいがら",
"Red Shard"	: 	"あかいかけら",
"Blue Shard"	: 	"あおいかけら",
"Yellow Shard"	: 	"きいろいかけら",
"Green Shard"	: 	"みどりのかけら",
"Super Repel"	: 	"シルバースプレー",
"Max Repel"	: 	"ゴールドスプレー",
"Escape Rope"	: 	"あなぬけのヒモ",
"Repel"	: 	"むしよけスプレー",
"Sun Stone"	: 	"たいようのいし",
"Moon Stone"	: 	"つきのいし",
"Fire Stone"	: 	"ほのおのいし",
"Thunder Stone"	: 	"かみなりのいし",
"Water Stone"	: 	"みずのいし",
"Leaf Stone"	: 	"リーフのいし",
"Tiny Mushroom"	: 	"ちいさなキノコ",
"Big Mushroom"	: 	"おおきなキノコ",
"Pearl"	: 	"しんじゅ",
"Big Pearl"	: 	"おおきなしんじゅ",
"Stardust"	: 	"ほしのすな",
"Star Piece"	: 	"ほしのかけら",
"Nugget"	: 	"きんのたま",
"Heart Scale"	: 	"ハートのウロコ",
"Honey"	: 	"あまいミツ",
"Growth Mulch"	: 	"すくすくこやし",
"Damp Mulch"	: 	"じめじめこやし",
"Stable Mulch"	: 	"ながながこやし",
"Gooey Mulch"	: 	"ねばねばこやし",
"Root Fossil"	: 	"ねっこのカセキ",
"Claw Fossil"	: 	"ツメのカセキ",
"Helix Fossil"	: 	"かいのカセキ",
"Dome Fossil"	: 	"こうらのカセキ",
"Old Amber"	: 	"ひみつのコハク",
"Armor Fossil"	: 	"たてのカセキ",
"Skull Fossil"	: 	"ずがいのカセキ",
"Rare Bone"	: 	"きちょうなホネ",
"Shiny Stone"	: 	"ひかりのいし",
"Dusk Stone"	: 	"やみのいし",
"Dawn Stone"	: 	"めざめいし",
"Oval Stone"	: 	"まんまるいし",
"Odd Keystone"	: 	"かなめいし",
"Griseous Orb"	: 	"はっきんだま",
"Tea"	: 	"おちゃ",
"???"	: 	"？？？",
"Autograph"	: 	"マチスのサイン",
"Douse Drive"	: 	"アクアカセット",
"Shock Drive"	: 	"イナズマカセット",
"Burn Drive"	: 	"ブレイズカセット",
"Chill Drive"	: 	"フリーズカセット",
"???"	: 	"？？？",
"Pokémon Box Link"	: 	"ポケモンボックス",
"Medicine Pocket"	: 	"かいふくポケット",
"TM Case"	: 	"わざマシンケース",
"Candy Jar"	: 	"アメボトル",
"Power-Up Pocket"	: 	"きょうかポケット",
"Clothing Trunk"	: 	"おきがえトランク",
"Catching Pocket"	: 	"ほかくポケット",
"Battle Pocket"	: 	"バトルポケット",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"Sweet Heart"	: 	"ハートスイーツ",
"Adamant Orb"	: 	"こんごうだま",
"Lustrous Orb"	: 	"しらたま",
"Greet Mail"	: 	"はじめてメール",
"Favored Mail"	: 	"だいすきメール",
"RSVP Mail"	: 	"おさそいメール",
"Thanks Mail"	: 	"かんしゃメール",
"Inquiry Mail"	: 	"しつもんメール",
"Like Mail"	: 	"おすすめメール",
"Reply Mail"	: 	"おかえしメール",
"Bridge Mail S"	: 	"ブリッジメールＳ",
"Bridge Mail D"	: 	"ブリッジメールＨ",
"Bridge Mail T"	: 	"ブリッジメールＣ",
"Bridge Mail V"	: 	"ブリッジメールＶ",
"Bridge Mail M"	: 	"ブリッジメールＷ",
"Cheri Berry"	: 	"クラボのみ",
"Chesto Berry"	: 	"カゴのみ",
"Pecha Berry"	: 	"モモンのみ",
"Rawst Berry"	: 	"チーゴのみ",
"Aspear Berry"	: 	"ナナシのみ",
"Leppa Berry"	: 	"ヒメリのみ",
"Oran Berry"	: 	"オレンのみ",
"Persim Berry"	: 	"キーのみ",
"Lum Berry"	: 	"ラムのみ",
"Sitrus Berry"	: 	"オボンのみ",
"Figy Berry"	: 	"フィラのみ",
"Wiki Berry"	: 	"ウイのみ",
"Mago Berry"	: 	"マゴのみ",
"Aguav Berry"	: 	"バンジのみ",
"Iapapa Berry"	: 	"イアのみ",
"Razz Berry"	: 	"ズリのみ",
"Bluk Berry"	: 	"ブリーのみ",
"Nanab Berry"	: 	"ナナのみ",
"Wepear Berry"	: 	"セシナのみ",
"Pinap Berry"	: 	"パイルのみ",
"Pomeg Berry"	: 	"ザロクのみ",
"Kelpsy Berry"	: 	"ネコブのみ",
"Qualot Berry"	: 	"タポルのみ",
"Hondew Berry"	: 	"ロメのみ",
"Grepa Berry"	: 	"ウブのみ",
"Tamato Berry"	: 	"マトマのみ",
"Cornn Berry"	: 	"モコシのみ",
"Magost Berry"	: 	"ゴスのみ",
"Rabuta Berry"	: 	"ラブタのみ",
"Nomel Berry"	: 	"ノメルのみ",
"Spelon Berry"	: 	"ノワキのみ",
"Pamtre Berry"	: 	"シーヤのみ",
"Watmel Berry"	: 	"カイスのみ",
"Durin Berry"	: 	"ドリのみ",
"Belue Berry"	: 	"ベリブのみ",
"Occa Berry"	: 	"オッカのみ",
"Passho Berry"	: 	"イトケのみ",
"Wacan Berry"	: 	"ソクノのみ",
"Rindo Berry"	: 	"リンドのみ",
"Yache Berry"	: 	"ヤチェのみ",
"Chople Berry"	: 	"ヨプのみ",
"Kebia Berry"	: 	"ビアーのみ",
"Shuca Berry"	: 	"シュカのみ",
"Coba Berry"	: 	"バコウのみ",
"Payapa Berry"	: 	"ウタンのみ",
"Tanga Berry"	: 	"タンガのみ",
"Charti Berry"	: 	"ヨロギのみ",
"Kasib Berry"	: 	"カシブのみ",
"Haban Berry"	: 	"ハバンのみ",
"Colbur Berry"	: 	"ナモのみ",
"Babiri Berry"	: 	"リリバのみ",
"Chilan Berry"	: 	"ホズのみ",
"Liechi Berry"	: 	"チイラのみ",
"Ganlon Berry"	: 	"リュガのみ",
"Salac Berry"	: 	"カムラのみ",
"Petaya Berry"	: 	"ヤタピのみ",
"Apicot Berry"	: 	"ズアのみ",
"Lansat Berry"	: 	"サンのみ",
"Starf Berry"	: 	"スターのみ",
"Enigma Berry"	: 	"ナゾのみ",
"Micle Berry"	: 	"ミクルのみ",
"Custap Berry"	: 	"イバンのみ",
"Jaboca Berry"	: 	"ジャポのみ",
"Rowap Berry"	: 	"レンブのみ",
"Bright Powder"	: 	"ひかりのこな",
"White Herb"	: 	"しろいハーブ",
"Macho Brace"	: 	"きょうせいギプス",
"Exp. Share"	: 	"がくしゅうそうち",
"Quick Claw"	: 	"せんせいのツメ",
"Soothe Bell"	: 	"やすらぎのすず",
"Mental Herb"	: 	"メンタルハーブ",
"Choice Band"	: 	"こだわりハチマキ",
"King’s Rock"	: 	"おうじゃのしるし",
"Silver Powder"	: 	"ぎんのこな",
"Amulet Coin"	: 	"おまもりこばん",
"Cleanse Tag"	: 	"きよめのおふだ",
"Soul Dew"	: 	"こころのしずく",
"Deep Sea Tooth"	: 	"しんかいのキバ",
"Deep Sea Scale"	: 	"しんかいのウロコ",
"Smoke Ball"	: 	"けむりだま",
"Everstone"	: 	"かわらずのいし",
"Focus Band"	: 	"きあいのハチマキ",
"Lucky Egg"	: 	"しあわせタマゴ",
"Scope Lens"	: 	"ピントレンズ",
"Metal Coat"	: 	"メタルコート",
"Leftovers"	: 	"たべのこし",
"Dragon Scale"	: 	"りゅうのウロコ",
"Light Ball"	: 	"でんきだま",
"Soft Sand"	: 	"やわらかいすな",
"Hard Stone"	: 	"かたいいし",
"Miracle Seed"	: 	"きせきのタネ",
"Black Glasses"	: 	"くろいメガネ",
"Black Belt"	: 	"くろおび",
"Magnet"	: 	"じしゃく",
"Mystic Water"	: 	"しんぴのしずく",
"Sharp Beak"	: 	"するどいくちばし",
"Poison Barb"	: 	"どくバリ",
"Never-Melt Ice"	: 	"とけないこおり",
"Spell Tag"	: 	"のろいのおふだ",
"Twisted Spoon"	: 	"まがったスプーン",
"Charcoal"	: 	"もくたん",
"Dragon Fang"	: 	"りゅうのキバ",
"Silk Scarf"	: 	"シルクのスカーフ",
"Upgrade"	: 	"アップグレード",
"Shell Bell"	: 	"かいがらのすず",
"Sea Incense"	: 	"うしおのおこう",
"Lax Incense"	: 	"のんきのおこう",
"Lucky Punch"	: 	"ラッキーパンチ",
"Metal Powder"	: 	"メタルパウダー",
"Thick Club"	: 	"ふといホネ",
"Leek"	: 	"ながねぎ",
"Red Scarf"	: 	"あかいバンダナ",
"Blue Scarf"	: 	"あおいバンダナ",
"Pink Scarf"	: 	"ピンクのバンダナ",
"Green Scarf"	: 	"みどりのバンダナ",
"Yellow Scarf"	: 	"きいろのバンダナ",
"Wide Lens"	: 	"こうかくレンズ",
"Muscle Band"	: 	"ちからのハチマキ",
"Wise Glasses"	: 	"ものしりメガネ",
"Expert Belt"	: 	"たつじんのおび",
"Light Clay"	: 	"ひかりのねんど",
"Life Orb"	: 	"いのちのたま",
"Power Herb"	: 	"パワフルハーブ",
"Toxic Orb"	: 	"どくどくだま",
"Flame Orb"	: 	"かえんだま",
"Quick Powder"	: 	"スピードパウダー",
"Focus Sash"	: 	"きあいのタスキ",
"Zoom Lens"	: 	"フォーカスレンズ",
"Metronome"	: 	"メトロノーム",
"Iron Ball"	: 	"くろいてっきゅう",
"Lagging Tail"	: 	"こうこうのしっぽ",
"Destiny Knot"	: 	"あかいいと",
"Black Sludge"	: 	"くろいヘドロ",
"Icy Rock"	: 	"つめたいいわ",
"Smooth Rock"	: 	"さらさらいわ",
"Heat Rock"	: 	"あついいわ",
"Damp Rock"	: 	"しめったいわ",
"Grip Claw"	: 	"ねばりのかぎづめ",
"Choice Scarf"	: 	"こだわりスカーフ",
"Sticky Barb"	: 	"くっつきバリ",
"Power Bracer"	: 	"パワーリスト",
"Power Belt"	: 	"パワーベルト",
"Power Lens"	: 	"パワーレンズ",
"Power Band"	: 	"パワーバンド",
"Power Anklet"	: 	"パワーアンクル",
"Power Weight"	: 	"パワーウエイト",
"Shed Shell"	: 	"きれいなぬけがら",
"Big Root"	: 	"おおきなねっこ",
"Choice Specs"	: 	"こだわりメガネ",
"Flame Plate"	: 	"ひのたまプレート",
"Splash Plate"	: 	"しずくプレート",
"Zap Plate"	: 	"いかずちプレート",
"Meadow Plate"	: 	"みどりのプレート",
"Icicle Plate"	: 	"つららのプレート",
"Fist Plate"	: 	"こぶしのプレート",
"Toxic Plate"	: 	"もうどくプレート",
"Earth Plate"	: 	"だいちのプレート",
"Sky Plate"	: 	"あおぞらプレート",
"Mind Plate"	: 	"ふしぎのプレート",
"Insect Plate"	: 	"たまむしプレート",
"Stone Plate"	: 	"がんせきプレート",
"Spooky Plate"	: 	"もののけプレート",
"Draco Plate"	: 	"りゅうのプレート",
"Dread Plate"	: 	"こわもてプレート",
"Iron Plate"	: 	"こうてつプレート",
"Odd Incense"	: 	"あやしいおこう",
"Rock Incense"	: 	"がんせきおこう",
"Full Incense"	: 	"まんぷくおこう",
"Wave Incense"	: 	"さざなみのおこう",
"Rose Incense"	: 	"おはなのおこう",
"Luck Incense"	: 	"こううんのおこう",
"Pure Incense"	: 	"きよめのおこう",
"Protector"	: 	"プロテクター",
"Electirizer"	: 	"エレキブースター",
"Magmarizer"	: 	"マグマブースター",
"Dubious Disc"	: 	"あやしいパッチ",
"Reaper Cloth"	: 	"れいかいのぬの",
"Razor Claw"	: 	"するどいツメ",
"Razor Fang"	: 	"するどいキバ",
"TM01"	: 	"わざマシン０１",
"TM02"	: 	"わざマシン０２",
"TM03"	: 	"わざマシン０３",
"TM04"	: 	"わざマシン０４",
"TM05"	: 	"わざマシン０５",
"TM06"	: 	"わざマシン０６",
"TM07"	: 	"わざマシン０７",
"TM08"	: 	"わざマシン０８",
"TM09"	: 	"わざマシン０９",
"TM10"	: 	"わざマシン１０",
"TM11"	: 	"わざマシン１１",
"TM12"	: 	"わざマシン１２",
"TM13"	: 	"わざマシン１３",
"TM14"	: 	"わざマシン１４",
"TM15"	: 	"わざマシン１５",
"TM16"	: 	"わざマシン１６",
"TM17"	: 	"わざマシン１７",
"TM18"	: 	"わざマシン１８",
"TM19"	: 	"わざマシン１９",
"TM20"	: 	"わざマシン２０",
"TM21"	: 	"わざマシン２１",
"TM22"	: 	"わざマシン２２",
"TM23"	: 	"わざマシン２３",
"TM24"	: 	"わざマシン２４",
"TM25"	: 	"わざマシン２５",
"TM26"	: 	"わざマシン２６",
"TM27"	: 	"わざマシン２７",
"TM28"	: 	"わざマシン２８",
"TM29"	: 	"わざマシン２９",
"TM30"	: 	"わざマシン３０",
"TM31"	: 	"わざマシン３１",
"TM32"	: 	"わざマシン３２",
"TM33"	: 	"わざマシン３３",
"TM34"	: 	"わざマシン３４",
"TM35"	: 	"わざマシン３５",
"TM36"	: 	"わざマシン３６",
"TM37"	: 	"わざマシン３７",
"TM38"	: 	"わざマシン３８",
"TM39"	: 	"わざマシン３９",
"TM40"	: 	"わざマシン４０",
"TM41"	: 	"わざマシン４１",
"TM42"	: 	"わざマシン４２",
"TM43"	: 	"わざマシン４３",
"TM44"	: 	"わざマシン４４",
"TM45"	: 	"わざマシン４５",
"TM46"	: 	"わざマシン４６",
"TM47"	: 	"わざマシン４７",
"TM48"	: 	"わざマシン４８",
"TM49"	: 	"わざマシン４９",
"TM50"	: 	"わざマシン５０",
"TM51"	: 	"わざマシン５１",
"TM52"	: 	"わざマシン５２",
"TM53"	: 	"わざマシン５３",
"TM54"	: 	"わざマシン５４",
"TM55"	: 	"わざマシン５５",
"TM56"	: 	"わざマシン５６",
"TM57"	: 	"わざマシン５７",
"TM58"	: 	"わざマシン５８",
"TM59"	: 	"わざマシン５９",
"TM60"	: 	"わざマシン６０",
"TM61"	: 	"わざマシン６１",
"TM62"	: 	"わざマシン６２",
"TM63"	: 	"わざマシン６３",
"TM64"	: 	"わざマシン６４",
"TM65"	: 	"わざマシン６５",
"TM66"	: 	"わざマシン６６",
"TM67"	: 	"わざマシン６７",
"TM68"	: 	"わざマシン６８",
"TM69"	: 	"わざマシン６９",
"TM70"	: 	"わざマシン７０",
"TM71"	: 	"わざマシン７１",
"TM72"	: 	"わざマシン７２",
"TM73"	: 	"わざマシン７３",
"TM74"	: 	"わざマシン７４",
"TM75"	: 	"わざマシン７５",
"TM76"	: 	"わざマシン７６",
"TM77"	: 	"わざマシン７７",
"TM78"	: 	"わざマシン７８",
"TM79"	: 	"わざマシン７９",
"TM80"	: 	"わざマシン８０",
"TM81"	: 	"わざマシン８１",
"TM82"	: 	"わざマシン８２",
"TM83"	: 	"わざマシン８３",
"TM84"	: 	"わざマシン８４",
"TM85"	: 	"わざマシン８５",
"TM86"	: 	"わざマシン８６",
"TM87"	: 	"わざマシン８７",
"TM88"	: 	"わざマシン８８",
"TM89"	: 	"わざマシン８９",
"TM90"	: 	"わざマシン９０",
"TM91"	: 	"わざマシン９１",
"TM92"	: 	"わざマシン９２",
"HM01"	: 	"ひでんマシン０１",
"HM02"	: 	"ひでんマシン０２",
"HM03"	: 	"ひでんマシン０３",
"HM04"	: 	"ひでんマシン０４",
"HM05"	: 	"ひでんマシン０５",
"HM06"	: 	"ひでんマシン０６",
"???"	: 	"？？？",
"???"	: 	"？？？",
"Explorer Kit"	: 	"たんけんセット",
"Loot Sack"	: 	"たからぶくろ",
"Rule Book"	: 	"ルールブック",
"Poké Radar"	: 	"ポケトレ",
"Point Card"	: 	"ポイントカード",
"Guidebook"	: 	"ぼうけんノート",
"Sticker Case"	: 	"シールいれ",
"Fashion Case"	: 	"アクセサリーいれ",
"Sticker Bag"	: 	"シールぶくろ",
"Pal Pad"	: 	"ともだちてちょう",
"Works Key"	: 	"はつでんしょキー",
"Old Charm"	: 	"こだいのおまもり",
"Galactic Key"	: 	"ギンガだんのカギ",
"Red Chain"	: 	"あかいくさり",
"Town Map"	: 	"タウンマップ",
"Vs. Seeker"	: 	"バトルサーチャー",
"Coin Case"	: 	"コインケース",
"Old Rod"	: 	"ボロのつりざお",
"Good Rod"	: 	"いいつりざお",
"Super Rod"	: 	"すごいつりざお",
"Sprayduck"	: 	"コダックじょうろ",
"Poffin Case"	: 	"ポフィンケース",
"Bike"	: 	"じてんしゃ",
"Suite Key"	: 	"ルームキー",
"Oak’s Letter"	: 	"オーキドのてがみ",
"Lunar Feather"	: 	"みかづきのはね",
"Member Card"	: 	"メンバーズカード",
"Azure Flute"	: 	"てんかいのふえ",
"S.S. Ticket"	: 	"ふねのチケット",
"Contest Pass"	: 	"コンテストパス",
"Magma Stone"	: 	"かざんのおきいし",
"Parcel"	: 	"おとどけもの",
"Coupon 1"	: 	"ひきかえけん１",
"Coupon 2"	: 	"ひきかえけん２",
"Coupon 3"	: 	"ひきかえけん３",
"Storage Key"	: 	"そうこのカギ",
"Secret Medicine"	: 	"ひでんのくすり",
"Vs. Recorder"	: 	"バトルレコーダー",
"Gracidea"	: 	"グラシデアのはな",
"Secret Key"	: 	"ひみつのカギ",
"Apricorn Box"	: 	"ぼんぐりケース",
"Unown Report"	: 	"アンノーンノート",
"Berry Pots"	: 	"きのみプランター",
"Dowsing Machine"	: 	"ダウジングマシン",
"Blue Card"	: 	"ブルーカード",
"Slowpoke Tail"	: 	"おいしいシッポ",
"Clear Bell"	: 	"とうめいなスズ",
"Card Key"	: 	"カードキー",
"Basement Key"	: 	"ちかのかぎ",
"Squirt Bottle"	: 	"ゼニガメじょうろ",
"Red Scale"	: 	"あかいウロコ",
"Lost Item"	: 	"おとしもの",
"Pass"	: 	"リニアパス",
"Machine Part"	: 	"きかいのぶひん",
"Silver Feather"	: 	"ぎんいろのはね",
"Rainbow Feather"	: 	"にじいろのはね",
"Mystery Egg"	: 	"ふしぎなタマゴ",
"Red Apricorn"	: 	"あかぼんぐり",
"Blue Apricorn"	: 	"あおぼんぐり",
"Yellow Apricorn"	: 	"きぼんぐり",
"Green Apricorn"	: 	"みどぼんぐり",
"Pink Apricorn"	: 	"ももぼんぐり",
"White Apricorn"	: 	"しろぼんぐり",
"Black Apricorn"	: 	"くろぼんぐり",
"Fast Ball"	: 	"スピードボール",
"Level Ball"	: 	"レベルボール",
"Lure Ball"	: 	"ルアーボール",
"Heavy Ball"	: 	"ヘビーボール",
"Love Ball"	: 	"ラブラブボール",
"Friend Ball"	: 	"フレンドボール",
"Moon Ball"	: 	"ムーンボール",
"Sport Ball"	: 	"コンペボール",
"Park Ball"	: 	"パークボール",
"Photo Album"	: 	"フォトアルバム",
"GB Sounds"	: 	"ＧＢプレイヤー",
"Tidal Bell"	: 	"うみなりのスズ",
"Rage Candy Bar"	: 	"いかりまんじゅう",
"Data Card 01"	: 	"データカード０１",
"Data Card 02"	: 	"データカード０２",
"Data Card 03"	: 	"データカード０３",
"Data Card 04"	: 	"データカード０４",
"Data Card 05"	: 	"データカード０５",
"Data Card 06"	: 	"データカード０６",
"Data Card 07"	: 	"データカード０７",
"Data Card 08"	: 	"データカード０８",
"Data Card 09"	: 	"データカード０９",
"Data Card 10"	: 	"データカード１０",
"Data Card 11"	: 	"データカード１１",
"Data Card 12"	: 	"データカード１２",
"Data Card 13"	: 	"データカード１３",
"Data Card 14"	: 	"データカード１４",
"Data Card 15"	: 	"データカード１５",
"Data Card 16"	: 	"データカード１６",
"Data Card 17"	: 	"データカード１７",
"Data Card 18"	: 	"データカード１８",
"Data Card 19"	: 	"データカード１９",
"Data Card 20"	: 	"データカード２０",
"Data Card 21"	: 	"データカード２１",
"Data Card 22"	: 	"データカード２２",
"Data Card 23"	: 	"データカード２３",
"Data Card 24"	: 	"データカード２４",
"Data Card 25"	: 	"データカード２５",
"Data Card 26"	: 	"データカード２６",
"Data Card 27"	: 	"データカード２７",
"Jade Orb"	: 	"もえぎいろのたま",
"Lock Capsule"	: 	"ロックカプセル",
"Red Orb"	: 	"べにいろのたま",
"Blue Orb"	: 	"あいいろのたま",
"Enigma Stone"	: 	"なぞのすいしょう",
"Prism Scale"	: 	"きれいなウロコ",
"Eviolite"	: 	"しんかのきせき",
"Float Stone"	: 	"かるいし",
"Rocky Helmet"	: 	"ゴツゴツメット",
"Air Balloon"	: 	"ふうせん",
"Red Card"	: 	"レッドカード",
"Ring Target"	: 	"ねらいのまと",
"Binding Band"	: 	"しめつけバンド",
"Absorb Bulb"	: 	"きゅうこん",
"Cell Battery"	: 	"じゅうでんち",
"Eject Button"	: 	"だっしゅつボタン",
"Fire Gem"	: 	"ほのおのジュエル",
"Water Gem"	: 	"みずのジュエル",
"Electric Gem"	: 	"でんきのジュエル",
"Grass Gem"	: 	"くさのジュエル",
"Ice Gem"	: 	"こおりのジュエル",
"Fighting Gem"	: 	"かくとうジュエル",
"Poison Gem"	: 	"どくのジュエル",
"Ground Gem"	: 	"じめんのジュエル",
"Flying Gem"	: 	"ひこうのジュエル",
"Psychic Gem"	: 	"エスパージュエル",
"Bug Gem"	: 	"むしのジュエル",
"Rock Gem"	: 	"いわのジュエル",
"Ghost Gem"	: 	"ゴーストジュエル",
"Dragon Gem"	: 	"ドラゴンジュエル",
"Dark Gem"	: 	"あくのジュエル",
"Steel Gem"	: 	"はがねのジュエル",
"Normal Gem"	: 	"ノーマルジュエル",
"Health Feather"	: 	"たいりょくのハネ",
"Muscle Feather"	: 	"きんりょくのハネ",
"Resist Feather"	: 	"ていこうのハネ",
"Genius Feather"	: 	"ちりょくのハネ",
"Clever Feather"	: 	"せいしんのハネ",
"Swift Feather"	: 	"しゅんぱつのハネ",
"Pretty Feather"	: 	"きれいなハネ",
"Cover Fossil"	: 	"ふたのカセキ",
"Plume Fossil"	: 	"はねのカセキ",
"Liberty Pass"	: 	"リバティチケット",
"Pass Orb"	: 	"デルダマ",
"Dream Ball"	: 	"ドリームボール",
"Poké Toy"	: 	"ポケじゃらし",
"Prop Case"	: 	"グッズケース",
"Dragon Skull"	: 	"ドラゴンのホネ",
"Balm Mushroom"	: 	"かおるキノコ",
"Big Nugget"	: 	"でかいきんのたま",
"Pearl String"	: 	"おだんごしんじゅ",
"Comet Shard"	: 	"すいせいのかけら",
"Relic Copper"	: 	"こだいのどうか",
"Relic Silver"	: 	"こだいのぎんか",
"Relic Gold"	: 	"こだいのきんか",
"Relic Vase"	: 	"こだいのツボ",
"Relic Band"	: 	"こだいのうでわ",
"Relic Statue"	: 	"こだいのせきぞう",
"Relic Crown"	: 	"こだいのおうかん",
"Casteliacone"	: 	"ヒウンアイス",
"Dire Hit 2"	: 	"クリティカット２",
"X Speed 2"	: 	"スピーダー２",
"X Sp. Atk 2"	: 	"ＳＰアップ２",
"X Sp. Def 2"	: 	"ＳＰガード２",
"X Defense 2"	: 	"ディフェンダー２",
"X Attack 2"	: 	"プラスパワー２",
"X Accuracy 2"	: 	"ヨクアタール２",
"X Speed 3"	: 	"スピーダー３",
"X Sp. Atk 3"	: 	"ＳＰアップ３",
"X Sp. Def 3"	: 	"ＳＰガード３",
"X Defense 3"	: 	"ディフェンダー３",
"X Attack 3"	: 	"プラスパワー３",
"X Accuracy 3"	: 	"ヨクアタール３",
"X Speed 6"	: 	"スピーダー６",
"X Sp. Atk 6"	: 	"ＳＰアップ６",
"X Sp. Def 6"	: 	"ＳＰガード６",
"X Defense 6"	: 	"ディフェンダー６",
"X Attack 6"	: 	"プラスパワー６",
"X Accuracy 6"	: 	"ヨクアタール６",
"Ability Urge"	: 	"スキルコール",
"Item Drop"	: 	"アイテムドロップ",
"Item Urge"	: 	"アイテムコール",
"Reset Urge"	: 	"フラットコール",
"Dire Hit 3"	: 	"クリティカット３",
"Light Stone"	: 	"ライトストーン",
"Dark Stone"	: 	"ダークストーン",
"TM93"	: 	"わざマシン９３",
"TM94"	: 	"わざマシン９４",
"TM95"	: 	"わざマシン９５",
"Xtransceiver"	: 	"ライブキャスター",
"???"	: 	"ゴッドストーン",
"Gram 1"	: 	"はいたつぶつ１",
"Gram 2"	: 	"はいたつぶつ２",
"Gram 3"	: 	"はいたつぶつ３",
"Xtransceiver"	: 	"ライブキャスター",
"Medal Box"	: 	"メダルボックス",
"DNA Splicers"	: 	"いでんしのくさび",
"DNA Splicers"	: 	"いでんしのくさび",
"Permit"	: 	"きょかしょう",
"Oval Charm"	: 	"まるいおまもり",
"Shiny Charm"	: 	"ひかるおまもり",
"Plasma Card"	: 	"プラズマカード",
"Grubby Hanky"	: 	"よごれたハンカチ",
"Colress Machine"	: 	"アクロママシーン",
"Dropped Item"	: 	"わすれもの",
"Dropped Item"	: 	"わすれもの",
"Reveal Glass"	: 	"うつしかがみ",
"Weakness Policy"	: 	"じゃくてんほけん",
"Assault Vest"	: 	"とつげきチョッキ",
"Holo Caster"	: 	"ホロキャスター",
"Prof’s Letter"	: 	"はかせのてがみ",
"Roller Skates"	: 	"ローラースケート",
"Pixie Plate"	: 	"せいれいプレート",
"Ability Capsule"	: 	"とくせいカプセル",
"Whipped Dream"	: 	"ホイップポップ",
"Sachet"	: 	"においぶくろ",
"Luminous Moss"	: 	"ひかりごけ",
"Snowball"	: 	"ゆきだま",
"Safety Goggles"	: 	"ぼうじんゴーグル",
"Poké Flute"	: 	"ポケモンのふえ",
"Rich Mulch"	: 	"たわわこやし",
"Surprise Mulch"	: 	"びっくりこやし",
"Boost Mulch"	: 	"ぐんぐんこやし",
"Amaze Mulch"	: 	"とんでもこやし",
"Gengarite"	: 	"ゲンガナイト",
"Gardevoirite"	: 	"サーナイトナイト",
"Ampharosite"	: 	"デンリュウナイト",
"Venusaurite"	: 	"フシギバナイト",
"Charizardite X"	: 	"リザードナイトＸ",
"Blastoisinite"	: 	"カメックスナイト",
"Mewtwonite X"	: 	"ミュウツナイトＸ",
"Mewtwonite Y"	: 	"ミュウツナイトＹ",
"Blazikenite"	: 	"バシャーモナイト",
"Medichamite"	: 	"チャーレムナイト",
"Houndoominite"	: 	"ヘルガナイト",
"Aggronite"	: 	"ボスゴドラナイト",
"Banettite"	: 	"ジュペッタナイト",
"Tyranitarite"	: 	"バンギラスナイト",
"Scizorite"	: 	"ハッサムナイト",
"Pinsirite"	: 	"カイロスナイト",
"Aerodactylite"	: 	"プテラナイト",
"Lucarionite"	: 	"ルカリオナイト",
"Abomasite"	: 	"ユキノオナイト",
"Kangaskhanite"	: 	"ガルーラナイト",
"Gyaradosite"	: 	"ギャラドスナイト",
"Absolite"	: 	"アブソルナイト",
"Charizardite Y"	: 	"リザードナイトＹ",
"Alakazite"	: 	"フーディナイト",
"Heracronite"	: 	"ヘラクロスナイト",
"Mawilite"	: 	"クチートナイト",
"Manectite"	: 	"ライボルトナイト",
"Garchompite"	: 	"ガブリアスナイト",
"Latiasite"	: 	"ラティアスナイト",
"Latiosite"	: 	"ラティオスナイト",
"Roseli Berry"	: 	"ロゼルのみ",
"Kee Berry"	: 	"アッキのみ",
"Maranga Berry"	: 	"タラプのみ",
"Sprinklotad"	: 	"ハスボーじょうろ",
"TM96"	: 	"わざマシン９６",
"TM97"	: 	"わざマシン９７",
"TM98"	: 	"わざマシン９８",
"TM99"	: 	"わざマシン９９",
"TM100"	: 	"わざマシン１００",
"Power Plant Pass"	: 	"はつでんしょパス",
"Mega Ring"	: 	"メガリング",
"Intriguing Stone"	: 	"すごそうないし",
"Common Stone"	: 	"ありふれたいし",
"Discount Coupon"	: 	"バーゲンチケット",
"Elevator Key"	: 	"エレベータのキー",
"TMV Pass"	: 	"ＴＭＶパス",
"Honor of Kalos"	: 	"カロスエンブレム",
"Adventure Guide"	: 	"たんけんこころえ",
"Strange Souvenir"	: 	"ふしぎなおきもの",
"Lens Case"	: 	"レンズケース",
"Makeup Bag"	: 	"コスメポーチ",
"Travel Trunk"	: 	"いしょうトランク",
"Lumiose Galette"	: 	"ミアレガレット",
"Shalour Sable"	: 	"シャラサブレ",
"Jaw Fossil"	: 	"アゴのカセキ",
"Sail Fossil"	: 	"ヒレのカセキ",
"Looker Ticket"	: 	"ハンサムチケット",
"Bike"	: 	"じてんしゃ",
"Holo Caster"	: 	"ホロキャスター",
"Fairy Gem"	: 	"ようせいジュエル",
"Mega Charm"	: 	"メガチャーム",
"Mega Glove"	: 	"メガグローブ",
"Mach Bike"	: 	"マッハじてんしゃ",
"Acro Bike"	: 	"ダートじてんしゃ",
"Wailmer Pail"	: 	"ホエルコじょうろ",
"Devon Parts"	: 	"デボンのにもつ",
"Soot Sack"	: 	"はいぶくろ",
"Basement Key"	: 	"ちかのカギ",
"Pokéblock Kit"	: 	"ポロックキット",
"Letter"	: 	"ダイゴへのてがみ",
"Eon Ticket"	: 	"むげんのチケット",
"Scanner"	: 	"たんちき",
"Go-Goggles"	: 	"ゴーゴーゴーグル",
"Meteorite"	: 	"いんせき",
"Key to Room 1"	: 	"１ごうしつのカギ",
"Key to Room 2"	: 	"２ごうしつのカギ",
"Key to Room 4"	: 	"４ごうしつのカギ",
"Key to Room 6"	: 	"６ごうしつのカギ",
"Storage Key"	: 	"そうこのカギ",
"Devon Scope"	: 	"デボンスコープ",
"S.S. Ticket"	: 	"ふねのチケット",
"HM07"	: 	"ひでんマシン０７",
"Devon Scuba Gear"	: 	"デボンボンベ",
"Contest Costume"	: 	"ライブスーツ",
"Contest Costume"	: 	"ライブドレス",
"Magma Suit"	: 	"マグマスーツ",
"Aqua Suit"	: 	"アクアスーツ",
"Pair of Tickets"	: 	"ペアチケット",
"Mega Bracelet"	: 	"メガバングル",
"Mega Pendant"	: 	"メガペンダント",
"Mega Glasses"	: 	"メガメガネ",
"Mega Anchor"	: 	"メガイカリ",
"Mega Stickpin"	: 	"メガラペルピン",
"Mega Tiara"	: 	"メガティアラ",
"Mega Anklet"	: 	"メガアンクレット",
"Meteorite"	: 	"いんせき",
"Swampertite"	: 	"ラグラージナイト",
"Sceptilite"	: 	"ジュカインナイト",
"Sablenite"	: 	"ヤミラミナイト",
"Altarianite"	: 	"チルタリスナイト",
"Galladite"	: 	"エルレイドナイト",
"Audinite"	: 	"タブンネナイト",
"Metagrossite"	: 	"メタグロスナイト",
"Sharpedonite"	: 	"サメハダナイト",
"Slowbronite"	: 	"ヤドランナイト",
"Steelixite"	: 	"ハガネールナイト",
"Pidgeotite"	: 	"ピジョットナイト",
"Glalitite"	: 	"オニゴーリナイト",
"Diancite"	: 	"ディアンシナイト",
"Prison Bottle"	: 	"いましめのツボ",
"Mega Cuff"	: 	"メガブレス",
"Cameruptite"	: 	"バクーダナイト",
"Lopunnite"	: 	"ミミロップナイト",
"Salamencite"	: 	"ボーマンダナイト",
"Beedrillite"	: 	"スピアナイト",
"Meteorite"	: 	"いんせき",
"Meteorite"	: 	"いんせき",
"Key Stone"	: 	"キーストーン",
"Meteorite Shard"	: 	"いんせきのかけら",
"Eon Flute"	: 	"むげんのふえ",
"Normalium Z"	: 	"ノーマルＺ",
"Firium Z"	: 	"ホノオＺ",
"Waterium Z"	: 	"ミズＺ",
"Electrium Z"	: 	"デンキＺ",
"Grassium Z"	: 	"クサＺ",
"Icium Z"	: 	"コオリＺ",
"Fightinium Z"	: 	"カクトウＺ",
"Poisonium Z"	: 	"ドクＺ",
"Groundium Z"	: 	"ジメンＺ",
"Flyinium Z"	: 	"ヒコウＺ",
"Psychium Z"	: 	"エスパーＺ",
"Buginium Z"	: 	"ムシＺ",
"Rockium Z"	: 	"イワＺ",
"Ghostium Z"	: 	"ゴーストＺ",
"Dragonium Z"	: 	"ドラゴンＺ",
"Darkinium Z"	: 	"アクＺ",
"Steelium Z"	: 	"ハガネＺ",
"Fairium Z"	: 	"フェアリーＺ",
"Pikanium Z"	: 	"ピカチュウＺ",
"Bottle Cap"	: 	"ぎんのおうかん",
"Gold Bottle Cap"	: 	"きんのおうかん",
"Z-Ring"	: 	"Ｚリング",
"Decidium Z"	: 	"ジュナイパーＺ",
"Incinium Z"	: 	"ガオガエンＺ",
"Primarium Z"	: 	"アシレーヌＺ",
"Tapunium Z"	: 	"カプＺ",
"Marshadium Z"	: 	"マーシャドーＺ",
"Aloraichium Z"	: 	"アロライＺ",
"Snorlium Z"	: 	"カビゴンＺ",
"Eevium Z"	: 	"イーブイＺ",
"Mewnium Z"	: 	"ミュウＺ",
"Normalium Z"	: 	"ノーマルＺ",
"Firium Z"	: 	"ホノオＺ",
"Waterium Z"	: 	"ミズＺ",
"Electrium Z"	: 	"デンキＺ",
"Grassium Z"	: 	"クサＺ",
"Icium Z"	: 	"コオリＺ",
"Fightinium Z"	: 	"カクトウＺ",
"Poisonium Z"	: 	"ドクＺ",
"Groundium Z"	: 	"ジメンＺ",
"Flyinium Z"	: 	"ヒコウＺ",
"Psychium Z"	: 	"エスパーＺ",
"Buginium Z"	: 	"ムシＺ",
"Rockium Z"	: 	"イワＺ",
"Ghostium Z"	: 	"ゴーストＺ",
"Dragonium Z"	: 	"ドラゴンＺ",
"Darkinium Z"	: 	"アクＺ",
"Steelium Z"	: 	"ハガネＺ",
"Fairium Z"	: 	"フェアリーＺ",
"Pikanium Z"	: 	"ピカチュウＺ",
"Decidium Z"	: 	"ジュナイパーＺ",
"Incinium Z"	: 	"ガオガエンＺ",
"Primarium Z"	: 	"アシレーヌＺ",
"Tapunium Z"	: 	"カプＺ",
"Marshadium Z"	: 	"マーシャドーＺ",
"Aloraichium Z"	: 	"アロライＺ",
"Snorlium Z"	: 	"カビゴンＺ",
"Eevium Z"	: 	"イーブイＺ",
"Mewnium Z"	: 	"ミュウＺ",
"Pikashunium Z"	: 	"サトピカＺ",
"Pikashunium Z"	: 	"サトピカＺ",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"Forage Bag"	: 	"ざいりょうぶくろ",
"Fishing Rod"	: 	"つりざお",
"Professor’s Mask"	: 	"はかせのふくめん",
"Festival Ticket"	: 	"フェスチケット",
"Sparkling Stone"	: 	"かがやくいし",
"Adrenaline Orb"	: 	"ビビリだま",
"Zygarde Cube"	: 	"ジガルデキューブ",
"???"	: 	"？？？",
"Ice Stone"	: 	"こおりのいし",
"Ride Pager"	: 	"ライドギア",
"Beast Ball"	: 	"ウルトラボール",
"Big Malasada"	: 	"おおきいマラサダ",
"Red Nectar"	: 	"くれないのミツ",
"Yellow Nectar"	: 	"やまぶきのミツ",
"Pink Nectar"	: 	"うすもものミツ",
"Purple Nectar"	: 	"むらさきのミツ",
"Sun Flute"	: 	"たいようのふえ",
"Moon Flute"	: 	"つきのふえ",
"???"	: 	"？？？",
"Enigmatic Card"	: 	"あやしいカード",
"Silver Razz Berry"	: 	"ぎんのズリのみ",
"Golden Razz Berry"	: 	"きんのズリのみ",
"Silver Nanab Berry"	: 	"ぎんのナナのみ",
"Golden Nanab Berry"	: 	"きんのナナのみ",
"Silver Pinap Berry"	: 	"ぎんのパイルのみ",
"Golden Pinap Berry"	: 	"きんのパイルのみ",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"Secret Key"	: 	"ひみつのカギ",
"S.S. Ticket"	: 	"ふねのチケット",
"Silph Scope"	: 	"シルフスコープ",
"Parcel"	: 	"おとどけもの",
"Card Key"	: 	"カードキー",
"Gold Teeth"	: 	"きんのいれば",
"Lift Key"	: 	"エレベータのカギ",
"Terrain Extender"	: 	"グランドコート",
"Protective Pads"	: 	"ぼうごパット",
"Electric Seed"	: 	"エレキシード",
"Psychic Seed"	: 	"サイコシード",
"Misty Seed"	: 	"ミストシード",
"Grassy Seed"	: 	"グラスシード",
"Stretchy Spring"	: 	"のびたバネ",
"Chalky Stone"	: 	"チョークいし",
"Marble"	: 	"ビーだま",
"Lone Earring"	: 	"かたっぽピアス",
"Beach Glass"	: 	"うみべのガラス",
"Gold Leaf"	: 	"きんのはっぱ",
"Silver Leaf"	: 	"ぎんのはっぱ",
"Polished Mud Ball"	: 	"ピカピカだんご",
"Tropical Shell"	: 	"なんごくかいがら",
"Leaf Letter"	: 	"このはのおてがみ",
"Leaf Letter"	: 	"このはのおてがみ",
"Small Bouquet"	: 	"ちいさなはなたば",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"Lure"	: 	"むしよせコロン",
"Super Lure"	: 	"シルバーコロン",
"Max Lure"	: 	"ゴールドコロン",
"Pewter Crunchies"	: 	"ニビあられ",
"Fighting Memory"	: 	"ファイトメモリ",
"Flying Memory"	: 	"フライングメモリ",
"Poison Memory"	: 	"ポイズンメモリ",
"Ground Memory"	: 	"グラウンドメモリ",
"Rock Memory"	: 	"ロックメモリ",
"Bug Memory"	: 	"バグメモリ",
"Ghost Memory"	: 	"ゴーストメモリ",
"Steel Memory"	: 	"スチールメモリ",
"Fire Memory"	: 	"ファイヤーメモリ",
"Water Memory"	: 	"ウオーターメモリ",
"Grass Memory"	: 	"グラスメモリ",
"Electric Memory"	: 	"エレクトロメモリ",
"Psychic Memory"	: 	"サイキックメモリ",
"Ice Memory"	: 	"アイスメモリ",
"Dragon Memory"	: 	"ドラゴンメモリ",
"Dark Memory"	: 	"ダークメモリ",
"Fairy Memory"	: 	"フェアリーメモリ",
"Solganium Z"	: 	"ソルガレオＺ",
"Lunalium Z"	: 	"ルナアーラＺ",
"Ultranecrozium Z"	: 	"ウルトラネクロＺ",
"Mimikium Z"	: 	"ミミッキュＺ",
"Lycanium Z"	: 	"ルガルガンＺ",
"Kommonium Z"	: 	"ジャラランガＺ",
"Solganium Z"	: 	"ソルガレオＺ",
"Lunalium Z"	: 	"ルナアーラＺ",
"Ultranecrozium Z"	: 	"ウルトラネクロＺ",
"Mimikium Z"	: 	"ミミッキュＺ",
"Lycanium Z"	: 	"ルガルガンＺ",
"Kommonium Z"	: 	"ジャラランガＺ",
"Z-Power Ring"	: 	"Ｚパワーリング",
"Pink Petal"	: 	"ももいろはなびら",
"Orange Petal"	: 	"だいだいはなびら",
"Blue Petal"	: 	"あおのはなびら",
"Red Petal"	: 	"あかのはなびら",
"Green Petal"	: 	"みどりのはなびら",
"Yellow Petal"	: 	"きいろのはなびら",
"Purple Petal"	: 	"むらさきはなびら",
"Rainbow Flower"	: 	"にじいろのはな",
"Surge Badge"	: 	"だいだいバッジ",
"N-Solarizer"	: 	"ネクロプラスソル",
"N-Lunarizer"	: 	"ネクロプラスルナ",
"N-Solarizer"	: 	"ネクロプラスソル",
"N-Lunarizer"	: 	"ネクロプラスルナ",
"Ilima’s Normalium Z"	: 	"イリマノーマルＺ",
"Left Poké Ball"	: 	"のこされたボール",
"Roto Hatch"	: 	"タマゴふかポン",
"Roto Bargain"	: 	"やすうりポン",
"Roto Prize Money"	: 	"おこづかいポン",
"Roto Exp. Points"	: 	"けいけんポン",
"Roto Friendship"	: 	"なつきポン",
"Roto Encounter"	: 	"みっけポン",
"Roto Stealth"	: 	"かくれポン",
"Roto HP Restore"	: 	"ＨＰかいふくポン",
"Roto PP Restore"	: 	"ＰＰかいふくポン",
"Roto Boost"	: 	"おうえんポン",
"Roto Catch"	: 	"つかまえポン",
"Health Candy"	: 	"げんきのアメ",
"Mighty Candy"	: 	"ちからのアメ",
"Tough Candy"	: 	"まもりのアメ",
"Smart Candy"	: 	"ちしきのアメ",
"Courage Candy"	: 	"こころのアメ",
"Quick Candy"	: 	"はやさのアメ",
"Health Candy L"	: 	"げんきのアメＬ",
"Mighty Candy L"	: 	"ちからのアメＬ",
"Tough Candy L"	: 	"まもりのアメＬ",
"Smart Candy L"	: 	"ちしきのアメＬ",
"Courage Candy L"	: 	"こころのアメＬ",
"Quick Candy L"	: 	"はやさのアメＬ",
"Health Candy XL"	: 	"げんきのアメＸＬ",
"Mighty Candy XL"	: 	"ちからのアメＸＬ",
"Tough Candy XL"	: 	"まもりのアメＸＬ",
"Smart Candy XL"	: 	"ちしきのアメＸＬ",
"Courage Candy XL"	: 	"こころのアメＸＬ",
"Quick Candy XL"	: 	"はやさのアメＸＬ",
"Bulbasaur Candy"	: 	"フシギダネのアメ",
"Charmander Candy"	: 	"ヒトカゲのアメ",
"Squirtle Candy"	: 	"ゼニガメのアメ",
"Caterpie Candy"	: 	"キャタピーのアメ",
"Weedle Candy"	: 	"ビードルのアメ",
"Pidgey Candy"	: 	"ポッポのアメ",
"Rattata Candy"	: 	"コラッタのアメ",
"Spearow Candy"	: 	"オニスズメのアメ",
"Ekans Candy"	: 	"アーボのアメ",
"Pikachu Candy"	: 	"ピカチュウのアメ",
"Sandshrew Candy"	: 	"サンドのアメ",
"Nidoran♀ Candy"	: 	"ニドラン♀のアメ",
"Nidoran♂ Candy"	: 	"ニドラン♂のアメ",
"Clefairy Candy"	: 	"ピッピのアメ",
"Vulpix Candy"	: 	"ロコンのアメ",
"Jigglypuff Candy"	: 	"プリンのアメ",
"Zubat Candy"	: 	"ズバットのアメ",
"Oddish Candy"	: 	"ナゾノクサのアメ",
"Paras Candy"	: 	"パラスのアメ",
"Venonat Candy"	: 	"コンパンのアメ",
"Diglett Candy"	: 	"ディグダのアメ",
"Meowth Candy"	: 	"ニャースのアメ",
"Psyduck Candy"	: 	"コダックのアメ",
"Mankey Candy"	: 	"マンキーのアメ",
"Growlithe Candy"	: 	"ガーディのアメ",
"Poliwag Candy"	: 	"ニョロモのアメ",
"Abra Candy"	: 	"ケーシィのアメ",
"Machop Candy"	: 	"ワンリキーのアメ",
"Bellsprout Candy"	: 	"マダツボミのアメ",
"Tentacool Candy"	: 	"メノクラゲのアメ",
"Geodude Candy"	: 	"イシツブテのアメ",
"Ponyta Candy"	: 	"ポニータのアメ",
"Slowpoke Candy"	: 	"ヤドンのアメ",
"Magnemite Candy"	: 	"コイルのアメ",
"Farfetch’d Candy"	: 	"カモネギのアメ",
"Doduo Candy"	: 	"ドードーのアメ",
"Seel Candy"	: 	"パウワウのアメ",
"Grimer Candy"	: 	"ベトベターのアメ",
"Shellder Candy"	: 	"シェルダーのアメ",
"Gastly Candy"	: 	"ゴースのアメ",
"Onix Candy"	: 	"イワークのアメ",
"Drowzee Candy"	: 	"スリープのアメ",
"Krabby Candy"	: 	"クラブのアメ",
"Voltorb Candy"	: 	"ビリリダマのアメ",
"Exeggcute Candy"	: 	"タマタマのアメ",
"Cubone Candy"	: 	"カラカラのアメ",
"Hitmonlee Candy"	: 	"サワムラーのアメ",
"Hitmonchan Candy"	: 	"エビワラーのアメ",
"Lickitung Candy"	: 	"ベロリンガのアメ",
"Koffing Candy"	: 	"ドガースのアメ",
"Rhyhorn Candy"	: 	"サイホーンのアメ",
"Chansey Candy"	: 	"ラッキーのアメ",
"Tangela Candy"	: 	"モンジャラのアメ",
"Kangaskhan Candy"	: 	"ガルーラのアメ",
"Horsea Candy"	: 	"タッツーのアメ",
"Goldeen Candy"	: 	"トサキントのアメ",
"Staryu Candy"	: 	"ヒトデマンのアメ",
"Mr. Mime Candy"	: 	"バリヤードのアメ",
"Scyther Candy"	: 	"ストライクのアメ",
"Jynx Candy"	: 	"ルージュラのアメ",
"Electabuzz Candy"	: 	"エレブーのアメ",
"Pinsir Candy"	: 	"カイロスのアメ",
"Tauros Candy"	: 	"ケンタロスのアメ",
"Magikarp Candy"	: 	"コイキングのアメ",
"Lapras Candy"	: 	"ラプラスのアメ",
"Ditto Candy"	: 	"メタモンのアメ",
"Eevee Candy"	: 	"イーブイのアメ",
"Porygon Candy"	: 	"ポリゴンのアメ",
"Omanyte Candy"	: 	"オムナイトのアメ",
"Kabuto Candy"	: 	"カブトのアメ",
"Aerodactyl Candy"	: 	"プテラのアメ",
"Snorlax Candy"	: 	"カビゴンのアメ",
"Articuno Candy"	: 	"フリーザーのアメ",
"Zapdos Candy"	: 	"サンダーのアメ",
"Moltres Candy"	: 	"ファイヤーのアメ",
"Dratini Candy"	: 	"ミニリュウのアメ",
"Mewtwo Candy"	: 	"ミュウツーのアメ",
"Mew Candy"	: 	"ミュウのアメ",
"Meltan Candy"	: 	"メルタンのアメ",
"Magmar Candy"	: 	"ブーバーのアメ",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"Endorsement"	: 	"すいせんじょう",
"Pokémon Box Link"	: 	"ポケモンボックス",
"Wishing Star"	: 	"ねがいぼし",
"Dynamax Band"	: 	"ダイマックスＢ",
"???"	: 	"？？？",
"???"	: 	"？？？",
"Fishing Rod"	: 	"つりざお",
"Rotom Bike"	: 	"ロトムじてんしゃ",
"???"	: 	"？？？",
"???"	: 	"？？？",
"Sausages"	: 	"あらびきヴルスト",
"Bob’s Food Tin"	: 	"ボブのかんづめ",
"Bach’s Food Tin"	: 	"バックのかんづめ",
"Tin of Beans"	: 	"マメかん",
"Bread"	: 	"しょくパン",
"Pasta"	: 	"パスタ",
"Mixed Mushrooms"	: 	"キノコパック",
"Smoke-Poke Tail"	: 	"しっぽのくんせい",
"Large Leek"	: 	"ふといながねぎ",
"Fancy Apple"	: 	"とくせんリンゴ",
"Brittle Bones"	: 	"かぼそいホネ",
"Pack of Potatoes"	: 	"ポテトパック",
"Pungent Root"	: 	"みずべのハーブ",
"Salad Mix"	: 	"やさいパック",
"Fried Food"	: 	"フライもりあわせ",
"Boiled Egg"	: 	"ゆでタマゴ",
"Camping Gear"	: 	"キャンプセット",
"???"	: 	"？？？",
"???"	: 	"？？？",
"Rusted Sword"	: 	"くちたけん",
"Rusted Shield"	: 	"くちたたて",
"Fossilized Bird"	: 	"カセキのトリ",
"Fossilized Fish"	: 	"カセキのサカナ",
"Fossilized Drake"	: 	"カセキのリュウ",
"Fossilized Dino"	: 	"カセキのクビナガ",
"Strawberry Sweet"	: 	"いちごアメざいく",
"Love Sweet"	: 	"ハートアメざいく",
"Berry Sweet"	: 	"ベリーアメざいく",
"Clover Sweet"	: 	"よつばアメざいく",
"Flower Sweet"	: 	"おはなアメざいく",
"Star Sweet"	: 	"スターアメざいく",
"Ribbon Sweet"	: 	"リボンアメざいく",
"Sweet Apple"	: 	"あまーいりんご",
"Tart Apple"	: 	"すっぱいりんご",
"Throat Spray"	: 	"のどスプレー",
"Eject Pack"	: 	"だっしゅつパック",
"Heavy-Duty Boots"	: 	"あつぞこブーツ",
"Blunder Policy"	: 	"からぶりほけん",
"Room Service"	: 	"ルームサービス",
"Utility Umbrella"	: 	"ばんのうがさ",
"Exp. Candy XS"	: 	"けいけんアメＸＳ",
"Exp. Candy S"	: 	"けいけんアメＳ",
"Exp. Candy M"	: 	"けいけんアメＭ",
"Exp. Candy L"	: 	"けいけんアメＬ",
"Exp. Candy XL"	: 	"けいけんアメＸＬ",
"Dynamax Candy"	: 	"ダイマックスアメ",
"TR00"	: 	"わざレコード００",
"TR01"	: 	"わざレコード０１",
"TR02"	: 	"わざレコード０２",
"TR03"	: 	"わざレコード０３",
"TR04"	: 	"わざレコード０４",
"TR05"	: 	"わざレコード０５",
"TR06"	: 	"わざレコード０６",
"TR07"	: 	"わざレコード０７",
"TR08"	: 	"わざレコード０８",
"TR09"	: 	"わざレコード０９",
"TR10"	: 	"わざレコード１０",
"TR11"	: 	"わざレコード１１",
"TR12"	: 	"わざレコード１２",
"TR13"	: 	"わざレコード１３",
"TR14"	: 	"わざレコード１４",
"TR15"	: 	"わざレコード１５",
"TR16"	: 	"わざレコード１６",
"TR17"	: 	"わざレコード１７",
"TR18"	: 	"わざレコード１８",
"TR19"	: 	"わざレコード１９",
"TR20"	: 	"わざレコード２０",
"TR21"	: 	"わざレコード２１",
"TR22"	: 	"わざレコード２２",
"TR23"	: 	"わざレコード２３",
"TR24"	: 	"わざレコード２４",
"TR25"	: 	"わざレコード２５",
"TR26"	: 	"わざレコード２６",
"TR27"	: 	"わざレコード２７",
"TR28"	: 	"わざレコード２８",
"TR29"	: 	"わざレコード２９",
"TR30"	: 	"わざレコード３０",
"TR31"	: 	"わざレコード３１",
"TR32"	: 	"わざレコード３２",
"TR33"	: 	"わざレコード３３",
"TR34"	: 	"わざレコード３４",
"TR35"	: 	"わざレコード３５",
"TR36"	: 	"わざレコード３６",
"TR37"	: 	"わざレコード３７",
"TR38"	: 	"わざレコード３８",
"TR39"	: 	"わざレコード３９",
"TR40"	: 	"わざレコード４０",
"TR41"	: 	"わざレコード４１",
"TR42"	: 	"わざレコード４２",
"TR43"	: 	"わざレコード４３",
"TR44"	: 	"わざレコード４４",
"TR45"	: 	"わざレコード４５",
"TR46"	: 	"わざレコード４６",
"TR47"	: 	"わざレコード４７",
"TR48"	: 	"わざレコード４８",
"TR49"	: 	"わざレコード４９",
"TR50"	: 	"わざレコード５０",
"TR51"	: 	"わざレコード５１",
"TR52"	: 	"わざレコード５２",
"TR53"	: 	"わざレコード５３",
"TR54"	: 	"わざレコード５４",
"TR55"	: 	"わざレコード５５",
"TR56"	: 	"わざレコード５６",
"TR57"	: 	"わざレコード５７",
"TR58"	: 	"わざレコード５８",
"TR59"	: 	"わざレコード５９",
"TR60"	: 	"わざレコード６０",
"TR61"	: 	"わざレコード６１",
"TR62"	: 	"わざレコード６２",
"TR63"	: 	"わざレコード６３",
"TR64"	: 	"わざレコード６４",
"TR65"	: 	"わざレコード６５",
"TR66"	: 	"わざレコード６６",
"TR67"	: 	"わざレコード６７",
"TR68"	: 	"わざレコード６８",
"TR69"	: 	"わざレコード６９",
"TR70"	: 	"わざレコード７０",
"TR71"	: 	"わざレコード７１",
"TR72"	: 	"わざレコード７２",
"TR73"	: 	"わざレコード７３",
"TR74"	: 	"わざレコード７４",
"TR75"	: 	"わざレコード７５",
"TR76"	: 	"わざレコード７６",
"TR77"	: 	"わざレコード７７",
"TR78"	: 	"わざレコード７８",
"TR79"	: 	"わざレコード７９",
"TR80"	: 	"わざレコード８０",
"TR81"	: 	"わざレコード８１",
"TR82"	: 	"わざレコード８２",
"TR83"	: 	"わざレコード８３",
"TR84"	: 	"わざレコード８４",
"TR85"	: 	"わざレコード８５",
"TR86"	: 	"わざレコード８６",
"TR87"	: 	"わざレコード８７",
"TR88"	: 	"わざレコード８８",
"TR89"	: 	"わざレコード８９",
"TR90"	: 	"わざレコード９０",
"TR91"	: 	"わざレコード９１",
"TR92"	: 	"わざレコード９２",
"TR93"	: 	"わざレコード９３",
"TR94"	: 	"わざレコード９４",
"TR95"	: 	"わざレコード９５",
"TR96"	: 	"わざレコード９６",
"TR97"	: 	"わざレコード９７",
"TR98"	: 	"わざレコード９８",
"TR99"	: 	"わざレコード９９",
"TM00"	: 	"わざマシン００",
"Lonely Mint"	: 	"さみしがりミント",
"Adamant Mint"	: 	"いじっぱりミント",
"Naughty Mint"	: 	"やんちゃミント",
"Brave Mint"	: 	"ゆうかんミント",
"Bold Mint"	: 	"ずぶといミント",
"Impish Mint"	: 	"わんぱくミント",
"Lax Mint"	: 	"のうてんきミント",
"Relaxed Mint"	: 	"のんきミント",
"Modest Mint"	: 	"ひかえめミント",
"Mild Mint"	: 	"おっとりミント",
"Rash Mint"	: 	"うっかりやミント",
"Quiet Mint"	: 	"れいせいミント",
"Calm Mint"	: 	"おだやかミント",
"Gentle Mint"	: 	"おとなしいミント",
"Careful Mint"	: 	"しんちょうミント",
"Sassy Mint"	: 	"なまいきミント",
"Timid Mint"	: 	"おくびょうミント",
"Hasty Mint"	: 	"せっかちミント",
"Jolly Mint"	: 	"ようきミント",
"Naive Mint"	: 	"むじゃきミント",
"Serious Mint"	: 	"まじめミント",
"Wishing Piece"	: 	"ねがいのかたまり",
"Cracked Pot"	: 	"われたポット",
"Chipped Pot"	: 	"かけたポット",
"Hi-tech Earbuds"	: 	"すごいみみせん",
"Fruit Bunch"	: 	"フサパック",
"Moomoo Cheese"	: 	"モーモーチーズ",
"Spice Mix"	: 	"スパイスセット",
"Fresh Cream"	: 	"しんせんクリーム",
"Packaged Curry"	: 	"レトルトカレー",
"Coconut Milk"	: 	"ヤシのミルク",
"Instant Noodles"	: 	"レトルトめん",
"Precooked Burger"	: 	"レトルトバーグ",
"Gigantamix"	: 	"キョダイパウダー",
"Wishing Chip"	: 	"ねがいのかけら",
"Rotom Bike"	: 	"ロトムじてんしゃ",
"Catching Charm"	: 	"ゆれないおまもり",
"???"	: 	"？？？",
"Old Letter"	: 	"ふるびたてがみ",
"Band Autograph"	: 	"バンドのサイン",
"Sonia’s Book"	: 	"ソニアのほん",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"???"	: 	"？？？",
"Rotom Catalog"	: 	"ロトムのカタログ",
"★And458"	: 	"★And458",
"★And15"	: 	"★And15",
"★And337"	: 	"★And337",
"★And603"	: 	"★And603",
"★And390"	: 	"★And390",
"★Sgr6879"	: 	"★Sgr6879",
"★Sgr6859"	: 	"★Sgr6859",
"★Sgr6913"	: 	"★Sgr6913",
"★Sgr7348"	: 	"★Sgr7348",
"★Sgr7121"	: 	"★Sgr7121",
"★Sgr6746"	: 	"★Sgr6746",
"★Sgr7194"	: 	"★Sgr7194",
"★Sgr7337"	: 	"★Sgr7337",
"★Sgr7343"	: 	"★Sgr7343",
"★Sgr6812"	: 	"★Sgr6812",
"★Sgr7116"	: 	"★Sgr7116",
"★Sgr7264"	: 	"★Sgr7264",
"★Sgr7597"	: 	"★Sgr7597",
"★Del7882"	: 	"★Del7882",
"★Del7906"	: 	"★Del7906",
"★Del7852"	: 	"★Del7852",
"★Psc596"	: 	"★Psc596",
"★Psc361"	: 	"★Psc361",
"★Psc510"	: 	"★Psc510",
"★Psc437"	: 	"★Psc437",
"★Psc8773"	: 	"★Psc8773",
"★Lep1865"	: 	"★Lep1865",
"★Lep1829"	: 	"★Lep1829",
"★Boo5340"	: 	"★Boo5340",
"★Boo5506"	: 	"★Boo5506",
"★Boo5435"	: 	"★Boo5435",
"★Boo5602"	: 	"★Boo5602",
"★Boo5733"	: 	"★Boo5733",
"★Boo5235"	: 	"★Boo5235",
"★Boo5351"	: 	"★Boo5351",
"★Hya3748"	: 	"★Hya3748",
"★Hya3903"	: 	"★Hya3903",
"★Hya3418"	: 	"★Hya3418",
"★Hya3482"	: 	"★Hya3482",
"★Hya3845"	: 	"★Hya3845",
"★Eri1084"	: 	"★Eri1084",
"★Eri472"	: 	"★Eri472",
"★Eri1666"	: 	"★Eri1666",
"★Eri897"	: 	"★Eri897",
"★Eri1231"	: 	"★Eri1231",
"★Eri874"	: 	"★Eri874",
"★Eri1298"	: 	"★Eri1298",
"★Eri1325"	: 	"★Eri1325",
"★Eri984"	: 	"★Eri984",
"★Eri1464"	: 	"★Eri1464",
"★Eri1393"	: 	"★Eri1393",
"★Eri850"	: 	"★Eri850",
"★Tau1409"	: 	"★Tau1409",
"★Tau1457"	: 	"★Tau1457",
"★Tau1165"	: 	"★Tau1165",
"★Tau1791"	: 	"★Tau1791",
"★Tau1910"	: 	"★Tau1910",
"★Tau1346"	: 	"★Tau1346",
"★Tau1373"	: 	"★Tau1373",
"★Tau1412"	: 	"★Tau1412",
"★CMa2491"	: 	"★CMa2491",
"★CMa2693"	: 	"★CMa2693",
"★CMa2294"	: 	"★CMa2294",
"★CMa2827"	: 	"★CMa2827",
"★CMa2282"	: 	"★CMa2282",
"★CMa2618"	: 	"★CMa2618",
"★CMa2657"	: 	"★CMa2657",
"★CMa2646"	: 	"★CMa2646",
"★UMa4905"	: 	"★UMa4905",
"★UMa4301"	: 	"★UMa4301",
"★UMa5191"	: 	"★UMa5191",
"★UMa5054"	: 	"★UMa5054",
"★UMa4295"	: 	"★UMa4295",
"★UMa4660"	: 	"★UMa4660",
"★UMa4554"	: 	"★UMa4554",
"★UMa4069"	: 	"★UMa4069",
"★UMa3569"	: 	"★UMa3569",
"★UMa3323"	: 	"★UMa3323",
"★UMa4033"	: 	"★UMa4033",
"★UMa4377"	: 	"★UMa4377",
"★UMa4375"	: 	"★UMa4375",
"★UMa4518"	: 	"★UMa4518",
"★UMa3594"	: 	"★UMa3594",
"★Vir5056"	: 	"★Vir5056",
"★Vir4825"	: 	"★Vir4825",
"★Vir4932"	: 	"★Vir4932",
"★Vir4540"	: 	"★Vir4540",
"★Vir4689"	: 	"★Vir4689",
"★Vir5338"	: 	"★Vir5338",
"★Vir4910"	: 	"★Vir4910",
"★Vir5315"	: 	"★Vir5315",
"★Vir5359"	: 	"★Vir5359",
"★Vir5409"	: 	"★Vir5409",
"★Vir5107"	: 	"★Vir5107",
"★Ari617"	: 	"★Ari617",
"★Ari553"	: 	"★Ari553",
"★Ari546"	: 	"★Ari546",
"★Ari951"	: 	"★Ari951",
"★Ori1713"	: 	"★Ori1713",
"★Ori2061"	: 	"★Ori2061",
"★Ori1790"	: 	"★Ori1790",
"★Ori1903"	: 	"★Ori1903",
"★Ori1948"	: 	"★Ori1948",
"★Ori2004"	: 	"★Ori2004",
"★Ori1852"	: 	"★Ori1852",
"★Ori1879"	: 	"★Ori1879",
"★Ori1899"	: 	"★Ori1899",
"★Ori1543"	: 	"★Ori1543",
"★Cas21"	: 	"★Cas21",
"★Cas168"	: 	"★Cas168",
"★Cas403"	: 	"★Cas403",
"★Cas153"	: 	"★Cas153",
"★Cas542"	: 	"★Cas542",
"★Cas219"	: 	"★Cas219",
"★Cas265"	: 	"★Cas265",
"★Cnc3572"	: 	"★Cnc3572",
"★Cnc3208"	: 	"★Cnc3208",
"★Cnc3461"	: 	"★Cnc3461",
"★Cnc3449"	: 	"★Cnc3449",
"★Cnc3429"	: 	"★Cnc3429",
"★Cnc3627"	: 	"★Cnc3627",
"★Cnc3268"	: 	"★Cnc3268",
"★Cnc3249"	: 	"★Cnc3249",
"★Com4968"	: 	"★Com4968",
"★Crv4757"	: 	"★Crv4757",
"★Crv4623"	: 	"★Crv4623",
"★Crv4662"	: 	"★Crv4662",
"★Crv4786"	: 	"★Crv4786",
"★Aur1708"	: 	"★Aur1708",
"★Aur2088"	: 	"★Aur2088",
"★Aur1605"	: 	"★Aur1605",
"★Aur2095"	: 	"★Aur2095",
"★Aur1577"	: 	"★Aur1577",
"★Aur1641"	: 	"★Aur1641",
"★Aur1612"	: 	"★Aur1612",
"★Pav7790"	: 	"★Pav7790",
"★Cet911"	: 	"★Cet911",
"★Cet681"	: 	"★Cet681",
"★Cet188"	: 	"★Cet188",
"★Cet539"	: 	"★Cet539",
"★Cet804"	: 	"★Cet804",
"★Cep8974"	: 	"★Cep8974",
"★Cep8162"	: 	"★Cep8162",
"★Cep8238"	: 	"★Cep8238",
"★Cep8417"	: 	"★Cep8417",
"★Cen5267"	: 	"★Cen5267",
"★Cen5288"	: 	"★Cen5288",
"★Cen551"	: 	"★Cen551",
"★Cen5459"	: 	"★Cen5459",
"★Cen5460"	: 	"★Cen5460",
"★CMi2943"	: 	"★CMi2943",
"★CMi2845"	: 	"★CMi2845",
"★Equ8131"	: 	"★Equ8131",
"★Vul7405"	: 	"★Vul7405",
"★UMi424"	: 	"★UMi424",
"★UMi5563"	: 	"★UMi5563",
"★UMi5735"	: 	"★UMi5735",
"★UMi6789"	: 	"★UMi6789",
"★Crt4287"	: 	"★Crt4287",
"★Lyr7001"	: 	"★Lyr7001",
"★Lyr7178"	: 	"★Lyr7178",
"★Lyr7106"	: 	"★Lyr7106",
"★Lyr7298"	: 	"★Lyr7298",
"★Ara6585"	: 	"★Ara6585",
"★Sco6134"	: 	"★Sco6134",
"★Sco6527"	: 	"★Sco6527",
"★Sco6553"	: 	"★Sco6553",
"★Sco5953"	: 	"★Sco5953",
"★Sco5984"	: 	"★Sco5984",
"★Sco6508"	: 	"★Sco6508",
"★Sco6084"	: 	"★Sco6084",
"★Sco5944"	: 	"★Sco5944",
"★Sco6630"	: 	"★Sco6630",
"★Sco6027"	: 	"★Sco6027",
"★Sco6247"	: 	"★Sco6247",
"★Sco6252"	: 	"★Sco6252",
"★Sco5928"	: 	"★Sco5928",
"★Sco6241"	: 	"★Sco6241",
"★Sco6165"	: 	"★Sco6165",
"★Tri544"	: 	"★Tri544",
"★Leo3982"	: 	"★Leo3982",
"★Leo4534"	: 	"★Leo4534",
"★Leo4357"	: 	"★Leo4357",
"★Leo4057"	: 	"★Leo4057",
"★Leo4359"	: 	"★Leo4359",
"★Leo4031"	: 	"★Leo4031",
"★Leo3852"	: 	"★Leo3852",
"★Leo3905"	: 	"★Leo3905",
"★Leo3773"	: 	"★Leo3773",
"★Gru8425"	: 	"★Gru8425",
"★Gru8636"	: 	"★Gru8636",
"★Gru8353"	: 	"★Gru8353",
"★Lib5685"	: 	"★Lib5685",
"★Lib5531"	: 	"★Lib5531",
"★Lib5787"	: 	"★Lib5787",
"★Lib5603"	: 	"★Lib5603",
"★Pup3165"	: 	"★Pup3165",
"★Pup3185"	: 	"★Pup3185",
"★Pup3045"	: 	"★Pup3045",
"★Cyg7924"	: 	"★Cyg7924",
"★Cyg7417"	: 	"★Cyg7417",
"★Cyg7796"	: 	"★Cyg7796",
"★Cyg8301"	: 	"★Cyg8301",
"★Cyg7949"	: 	"★Cyg7949",
"★Cyg7528"	: 	"★Cyg7528",
"★Oct7228"	: 	"★Oct7228",
"★Col1956"	: 	"★Col1956",
"★Col2040"	: 	"★Col2040",
"★Col2177"	: 	"★Col2177",
"★Gem2990"	: 	"★Gem2990",
"★Gem2891"	: 	"★Gem2891",
"★Gem2421"	: 	"★Gem2421",
"★Gem2473"	: 	"★Gem2473",
"★Gem2216"	: 	"★Gem2216",
"★Gem2777"	: 	"★Gem2777",
"★Gem2650"	: 	"★Gem2650",
"★Gem2286"	: 	"★Gem2286",
"★Gem2484"	: 	"★Gem2484",
"★Gem2930"	: 	"★Gem2930",
"★Peg8775"	: 	"★Peg8775",
"★Peg8781"	: 	"★Peg8781",
"★Peg39"	: 	"★Peg39",
"★Peg8308"	: 	"★Peg8308",
"★Peg8650"	: 	"★Peg8650",
"★Peg8634"	: 	"★Peg8634",
"★Peg8684"	: 	"★Peg8684",
"★Peg8450"	: 	"★Peg8450",
"★Peg8880"	: 	"★Peg8880",
"★Peg8905"	: 	"★Peg8905",
"★Oph6556"	: 	"★Oph6556",
"★Oph6378"	: 	"★Oph6378",
"★Oph6603"	: 	"★Oph6603",
"★Oph6149"	: 	"★Oph6149",
"★Oph6056"	: 	"★Oph6056",
"★Oph6075"	: 	"★Oph6075",
"★Ser5854"	: 	"★Ser5854",
"★Ser7141"	: 	"★Ser7141",
"★Ser5879"	: 	"★Ser5879",
"★Her6406"	: 	"★Her6406",
"★Her6148"	: 	"★Her6148",
"★Her6410"	: 	"★Her6410",
"★Her6526"	: 	"★Her6526",
"★Her6117"	: 	"★Her6117",
"★Her6008"	: 	"★Her6008",
"★Per936"	: 	"★Per936",
"★Per1017"	: 	"★Per1017",
"★Per1131"	: 	"★Per1131",
"★Per1228"	: 	"★Per1228",
"★Per834"	: 	"★Per834",
"★Per941"	: 	"★Per941",
"★Phe99"	: 	"★Phe99",
"★Phe338"	: 	"★Phe338",
"★Vel3634"	: 	"★Vel3634",
"★Vel3485"	: 	"★Vel3485",
"★Vel3734"	: 	"★Vel3734",
"★Aqr8232"	: 	"★Aqr8232",
"★Aqr8414"	: 	"★Aqr8414",
"★Aqr8709"	: 	"★Aqr8709",
"★Aqr8518"	: 	"★Aqr8518",
"★Aqr7950"	: 	"★Aqr7950",
"★Aqr8499"	: 	"★Aqr8499",
"★Aqr8610"	: 	"★Aqr8610",
"★Aqr8264"	: 	"★Aqr8264",
"★Cru4853"	: 	"★Cru4853",
"★Cru4730"	: 	"★Cru4730",
"★Cru4763"	: 	"★Cru4763",
"★Cru4700"	: 	"★Cru4700",
"★Cru4656"	: 	"★Cru4656",
"★PsA8728"	: 	"★PsA8728",
"★TrA6217"	: 	"★TrA6217",
"★Cap7776"	: 	"★Cap7776",
"★Cap7754"	: 	"★Cap7754",
"★Cap8278"	: 	"★Cap8278",
"★Cap8322"	: 	"★Cap8322",
"★Cap7773"	: 	"★Cap7773",
"★Sge7479"	: 	"★Sge7479",
"★Car2326"	: 	"★Car2326",
"★Car3685"	: 	"★Car3685",
"★Car3307"	: 	"★Car3307",
"★Car3699"	: 	"★Car3699",
"★Dra5744"	: 	"★Dra5744",
"★Dra5291"	: 	"★Dra5291",
"★Dra6705"	: 	"★Dra6705",
"★Dra6536"	: 	"★Dra6536",
"★Dra7310"	: 	"★Dra7310",
"★Dra6688"	: 	"★Dra6688",
"★Dra4434"	: 	"★Dra4434",
"★Dra6370"	: 	"★Dra6370",
"★Dra7462"	: 	"★Dra7462",
"★Dra6396"	: 	"★Dra6396",
"★Dra6132"	: 	"★Dra6132",
"★Dra6636"	: 	"★Dra6636",
"★CVn4915"	: 	"★CVn4915",
"★CVn4785"	: 	"★CVn4785",
"★CVn4846"	: 	"★CVn4846",
"★Aql7595"	: 	"★Aql7595",
"★Aql7557"	: 	"★Aql7557",
"★Aql7525"	: 	"★Aql7525",
"★Aql7602"	: 	"★Aql7602",
"★Aql7235"	: 	"★Aql7235",
"Max Honey"	: 	"ダイミツ",
"Max Mushrooms"	: 	"ダイキノコ",
"Galarica Twig"	: 	"ガラナツのえだ",
"Galarica Cuff"	: 	"ガラナツブレス",
"Style Card"	: 	"おしゃれカード",
"Armor Pass"	: 	"ヨロイパス",
"Rotom Bike"	: 	"ロトムじてんしゃ",
"Rotom Bike"	: 	"ロトムじてんしゃ",
"Exp. Charm"	: 	"けいけんおまもり",
"Armorite Ore"	: 	"ヨロイこうせき",
"Mark Charm"	: 	"あかしのおまもり",
"Reins of Unity"	: 	"キズナのタヅナ",
"Reins of Unity"	: 	"キズナのタヅナ",
"Galarica Wreath"	: 	"ガラナツリース",
"Legendary Clue 1"	: 	"でんせつのメモ１",
"Legendary Clue 2"	: 	"でんせつのメモ２",
"Legendary Clue 3"	: 	"でんせつのメモ３",
"Legendary Clue?"	: 	"でんせつのメモ？",
"Crown Pass"	: 	"カンムリパス",
"Wooden Crown"	: 	"きぼりのかんむり",
"Radiant Petal"	: 	"かがやくはなびら",
"White Mane Hair"	: 	"しろいたてがみ",
"Black Mane Hair"	: 	"くろいたてがみ",
"Iceroot Carrot"	: 	"つめたいにんじん",
"Shaderoot Carrot"	: 	"くろいにんじん",
"Dynite Ore"	: 	"マックスこうせき",
"Carrot Seeds"	: 	"にんじんのタネ",
"Ability Patch"	: 	"とくせいパッチ",
"Reins of Unity"	: 	"キズナのタヅナ",
"Time Balm"	: 	"ときのシズメダマ",
"Space Balm"	: 	"そらのシズメダマ",
"Mysterious Balm"	: 	"しずめだま",
"Linking Cord"	: 	"つながりのヒモ",
"Hometown Muffin"	: 	"ふるさとマフィン",
"Apricorn"	: 	"ぼんぐりのみ",
"Jubilife Muffin"	: 	"コトブキマフィン",
"Aux Powerguard"	: 	"ビルドアッパー",
"Dire Hit"	: 	"クリティカッター",
"Choice Dumpling"	: 	"こだわりちまき",
"Twice-Spiced Radish"	: 	"にばいづけ",
"Swap Snack"	: 	"あべこべやき",
"Caster Fern"	: 	"まるいはっぱ",
"Seed of Mastery"	: 	"たくみのえまき",
"Poké Ball"	: 	"モンスターボール",
"???"	: 	"ススキのおとしもの",
"Eternal Ice"	: 	"こだいのこおり",
"Uxie’s Claw"	: 	"ユクシーのつめ",
"Azelf’s Fang"	: 	"アグノムのきば",
"Mesprit’s Plume"	: 	"エムリットのはね",
"Tumblestone"	: 	"たまいし",
"Celestica Flute"	: 	"カミナギのふえ",
"Remedy"	: 	"カンポーやく",
"Fine Remedy"	: 	"いいカンポーやく",
"Dazzling Honey"	: 	"きらきらミツ",
"Hearty Grains"	: 	"いきいきイナホ",
"Plump Beans"	: 	"ころころマメ",
"Springy Mushroom"	: 	"もちもちキノコ",
"Crunchy Salt"	: 	"ごりごりミネラル",
"Wood"	: 	"もくざい",
"King’s Leaf"	: 	"キングリーフ",
"Marsh Balm"	: 	"シズメダマ２",
"Poké Ball"	: 	"モンスターボール",
"Great Ball"	: 	"スーパーボール",
"Ultra Ball"	: 	"ハイパーボール",
"Feather Ball"	: 	"クラフトレシピ４１",
"Pokéshi Doll"	: 	"ポケモンこけし",
"???"	: 	"クラフトレシピ０６",
"Smoke Bomb"	: 	"クラフトレシピ０７",
"Scatter Bang"	: 	"ばりばりだま",
"Sticky Glob"	: 	"ねばりだま",
"Star Piece"	: 	"クラフトレシピ１０",
"Mushroom Cake"	: 	"クラフトレシピ１１",
"Bugwort"	: 	"むらさきハーブ",
"Honey Cake"	: 	"クラフトレシピ１２",
"Grain Cake"	: 	"クラフトレシピ１３",
"Bean Cake"	: 	"クラフトレシピ１４",
"Salt Cake"	: 	"クラフトレシピ１５",
"Potion"	: 	"クラフトレシピ１６",
"Super Potion"	: 	"クラフトレシピ１７",
"Hyper Potion"	: 	"クラフトレシピ１８",
"Max Potion"	: 	"クラフトレシピ１９",
"Full Restore"	: 	"クラフトレシピ２０",
"Remedy"	: 	"クラフトレシピ２１",
"Fine Remedy"	: 	"クラフトレシピ２２",
"Superb Remedy"	: 	"クラフトレシピ２３",
"Old Gateau"	: 	"クラフトレシピ２４",
"Jubilife Muffin"	: 	"クラフトレシピ２５",
"Full Heal"	: 	"クラフトレシピ２６",
"Revive"	: 	"クラフトレシピ２７",
"Max Revive"	: 	"クラフトレシピ２８",
"Max Ether"	: 	"クラフトレシピ２９",
"Max Elixir"	: 	"クラフトレシピ３０",
"Stealth Spray"	: 	"クラフトレシピ３１",
"???"	: 	"？？？",
"Aux Power"	: 	"クラフトレシピ３３",
"Aux Guard"	: 	"クラフトレシピ３４",
"Dire Hit"	: 	"クラフトレシピ３５",
"Aux Evasion"	: 	"クラフトレシピ３６",
"Aux Powerguard"	: 	"クラフトレシピ３７",
"Forest Balm"	: 	"しずめダマ",
"Iron Chunk"	: 	"てつのかけら",
"???"	: 	"？？？",
"Black Tumblestone"	: 	"くろいろたまいし",
"Sky Tumblestone"	: 	"そらいろたまいし",
"???"	: 	"？？？",
"Ball of Mud"	: 	"どろだんご",
"???"	: 	"？？？",
"Pop Pod"	: 	"バリバリモズク",
"Sootfoot Root"	: 	"ケムリイモ",
"Spoiled Apricorn"	: 	"むしくいぼんぐり",
"Snowball"	: 	"ゆきだま",
"Sticky Glob"	: 	"ねばりだま",
"Black Augurite"	: 	"くろのきせき",
"Peat Block"	: 	"ピートブロック",
"Stealth Spray"	: 	"むしよけスプレー",
"Medicinal Leek"	: 	"クスリソウ",
"Vivichoke"	: 	"ゲンキツボミ",
"Pep-Up Plant"	: 	"ピーピーグサ",
"???"	: 	"？？？",
"???"	: 	"？？？",
"Tempting Charm B"	: 	"ふしぎなおまもり２（仮）",
"Tempting Charm P"	: 	"ふしぎなおまもり３（仮）",
"Swordcap"	: 	"ツルギマイタケ",
"Iron Barktongue"	: 	"テッペキクラゲ",
"Doppel Bonnets"	: 	"カゲブンシメジ（仮）",
"Direshroom"	: 	"キュウショウロ（仮）",
"Sand Radish"	: 	"すなはまダイコン",
"Tempting Charm T"	: 	"ふしぎなおまもり４（仮）",
"Tempting Charm Y"	: 	"ふしぎなおまもり５（仮）",
"Candy Truffle"	: 	"スイートトリュフ",
"Cake-Lure Base"	: 	"よせだまのもと",
"Poké Ball"	: 	"モンスターボール",
"Great Ball"	: 	"スーパーボール",
"Ultra Ball"	: 	"ハイパーボール",
"Feather Ball"	: 	"フェザーボール",
"???"	: 	"アーチボール",
"???"	: 	"とくしゅボール",
"Scatter Bang"	: 	"ビビリだま",
"Smoke Bomb"	: 	"けむりだま",
"???"	: 	"？？？",
"???"	: 	"？？？",
"Pokéshi Doll"	: 	"ポケモンこけし",
"Volcano Balm"	: 	"かざんのシズメダマ",
"Mountain Balm"	: 	"やまのシズメダマ",
"Snow Balm"	: 	"ゆきのシズメダマ",
"Honey Cake"	: 	"ミツよせだま",
"Grain Cake"	: 	"イナホよせだま",
"Bean Cake"	: 	"マメよせだま",
"Mushroom Cake"	: 	"キノコよせだま",
"Salt Cake"	: 	"ミネラルよせだま",
"Swap Snack"	: 	"クラフトレシピ３８",
"Choice Dumpling"	: 	"クラフトレシピ３９",
"Twice-Spiced Radish"	: 	"クラフトレシピ４０",
"Survival Charm R"	: 	"あんぜんおまもり１",
"Survival Charm B"	: 	"あんぜんおまもり２",
"Survival Charm P"	: 	"あんぜんおまもり３",
"Survival Charm T"	: 	"あんぜんおまもり４",
"Survival Charm Y"	: 	"あんぜんおまもり５",
"Torn Journal"	: 	"やぶれたにっき",
"Warding Charm R"	: 	"けんこうおまもり１",
"Warding Charm B"	: 	"けんこうおまもり２",
"Warding Charm P"	: 	"けんこうおまもり３",
"Warding Charm T"	: 	"けんこうおまもり４",
"Warding Charm Y"	: 	"けんこうおまもり５",
"Wall Fragment"	: 	"せきばんのかけら",
"Basculegion Food"	: 	"イダイトウだんご",
"Old Journal"	: 	"ふるいにっき",
"Wing Ball"	: 	"ウイングボール",
"Jet Ball"	: 	"ジェットボール",
"Heavy Ball"	: 	"ヘビーボール",
"Leaden Ball"	: 	"メガトンボール",
"Gigaton Ball"	: 	"ギガトンボール",
"Wing Ball"	: 	"ウイングボール",
"Jet Ball"	: 	"クラフトレシピ４２",
"Heavy Ball"	: 	"クラフトレシピ４３",
"Hopo Berry"	: 	"ポフのみ",
"Superb Remedy"	: 	"すごいカンポーやく",
"Aux Power"	: 	"アタックアップ",
"Aux Guard"	: 	"ディフェンスアップ",
"Aux Evasion"	: 	"ヨクアタラーヌ",
"Grit Dust"	: 	"ガンバリのすな",
"Grit Gravel"	: 	"ガンバリのじゃり",
"Grit Pebble"	: 	"ガンバリのいし",
"Grit Rock"	: 	"ガンバリのいわ",
"Secret Medicine"	: 	"ガンバリセット",
"Tempting Charm R"	: 	"ふしぎなおまもり",
"Lost Satchel"	: 	"だれかのポーチ",
"Lost Satchel"	: 	"だれかのポーチ",
"Lost Satchel"	: 	"だれかのポーチ",
"Lost Satchel"	: 	"だれかのポーチ",
"Lost Satchel"	: 	"だれかのポーチ",
"???"	: 	"スマートフォン",
"Origin Ball"	: 	"オリジンボール",
"???"	: 	"だれかのきんちゃく",
"???"	: 	"タマカゴ",
"???"	: 	"だんいんしょう",
"???"	: 	"くさりのはへん",
"Origin Ore"	: 	"オリジンこうせき",
"Adamant Crystal"	: 	"だいこんごうだま",
"Lustrous Globe"	: 	"だいしらたま",
"Griseous Core"	: 	"だいはっきんだま",
"Blank Plate"	: 	"まっさらプレート",
"???"	: 	"？？？",
"Crafting Kit"	: 	"クラフトキット",
"Leaden Ball"	: 	"クラフトレシピ４４",
"Gigaton Ball"	: 	"クラフトレシピ４５",
"Strange Ball"	: 	"ストレンジボール",
"Pokédex"	: 	"ポケモンずかん",
"Old Verse 1"	: 	"ふるいポエム１",
"Old Verse 2"	: 	"ふるいポエム２",
"Old Verse 3"	: 	"ふるいポエム３",
"Old Verse 4"	: 	"ふるいポエム４",
"???"	: 	"アルセウスフォン",
"Old Verse 5"	: 	"ふるいポエム５",
"Old Verse 6"	: 	"ふるいポエム６",
"Old Verse 7"	: 	"ふるいポエム７",
"Old Verse 8"	: 	"ふるいポエム８",
"Old Verse 9"	: 	"ふるいポエム９",
"Old Verse 10"	: 	"ふるいポエム１０",
"Old Verse 11"	: 	"ふるいポエム１１",
"Old Verse 12"	: 	"ふるいポエム１２",
"Old Verse 13"	: 	"ふるいポエム１３",
"Old Verse 14"	: 	"ふるいポエム１４",
"Old Verse 15"	: 	"ふるいポエム１５",
"Old Verse 16"	: 	"ふるいポエム１６",
"Old Verse 17"	: 	"ふるいポエム１７",
"Old Verse 18"	: 	"ふるいポエム１８",
"Old Verse 19"	: 	"ふるいポエム１９",
"Old Verse 20"	: 	"ふるいポエム２０",
"Mysterious Shard S"	: 	"なぞのかけらＳ",
"Mysterious Shard L"	: 	"なぞのかけらＬ",
"Digger Drill"	: 	"あなほりドリル",
"Kanto Slate"	: 	"カントーのせきばん",
"Johto Slate"	: 	"ジョウトのせきばん",
"Soul Slate"	: 	"こころのせきばん",
"Rainbow Slate"	: 	"にじのせきばん",
"Squall Slate"	: 	"あらしのせきばん",
"Oceanic Slate"	: 	"たいかいのせきばん",
"Tectonic Slate"	: 	"たいりくのせきばん",
"Stratospheric Slate"	: 	"てんくうのせきばん",
"Genome Slate"	: 	"いでんしのせきばん",
"Discovery Slate"	: 	"みちびきのせきばん",
"Distortion Slate"	: 	"やぶれたせきばん",
"DS Sounds"	: 	"ＤＳプレイヤー",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
"Legend Plate"	: 	"レジェンドプレート",
"Rotom Phone"	: 	"スマホロトム",
"Sandwich"	: 	"サンドウィッチ",
"Koraidon’s Poké Ball"	: 	"コライドンのボール",
"Miraidon’s Poké Ball"	: 	"ミライドンのボール",
"Tera Orb"	: 	"テラスタルオーブ",
"Scarlet Book"	: 	"スカーレットブック",
"Violet Book"	: 	"バイオレットブック",
"Kofu’s Wallet"	: 	"ハイダイのサイフ",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
"Tiny Bamboo Shoot"	: 	"ちいさなタケノコ",
"Big Bamboo Shoot"	: 	"おおきなタケノコ",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
"Scroll of Darkness"	: 	"あくのかけじく",
"Scroll of Waters"	: 	"みずのかけじく",
""	: 	"",
""	: 	"",
"Malicious Armor"	: 	"ノロイノヨロイ",
"Normal Tera Shard"	: 	"テラピースノーマル",
"Fire Tera Shard"	: 	"テラピースほのお",
"Water Tera Shard"	: 	"テラピースみず",
"Electric Tera Shard"	: 	"テラピースでんき",
"Grass Tera Shard"	: 	"テラピースくさ",
"Ice Tera Shard"	: 	"テラピースこおり",
"Fighting Tera Shard"	: 	"テラピースかくとう",
"Poison Tera Shard"	: 	"テラピースどく",
"Ground Tera Shard"	: 	"テラピースじめん",
"Flying Tera Shard"	: 	"テラピースひこう",
"Psychic Tera Shard"	: 	"テラピースエスパー",
"Bug Tera Shard"	: 	"テラピースむし",
"Rock Tera Shard"	: 	"テラピースいわ",
"Ghost Tera Shard"	: 	"テラピースゴースト",
"Dragon Tera Shard"	: 	"テラピースドラゴン",
"Dark Tera Shard"	: 	"テラピースあく",
"Steel Tera Shard"	: 	"テラピースはがね",
"Fairy Tera Shard"	: 	"テラピースフェアリー",
"Booster Energy"	: 	"ブーストエナジー",
"Ability Shield"	: 	"とくせいガード",
"Clear Amulet"	: 	"クリアチャーム",
"Mirror Herb"	: 	"ものまねハーブ",
"Punching Glove"	: 	"パンチグローブ",
"Covert Cloak"	: 	"おんみつマント",
"Loaded Dice"	: 	"いかさまダイス",
""	: 	"",
"Baguette"	: 	"バゲット",
"Mayonnaise"	: 	"マヨネーズ",
"Ketchup"	: 	"ケチャップ",
"Mustard"	: 	"マスタード",
"Butter"	: 	"バター",
"Peanut Butter"	: 	"ピーナッツバター",
"Chili Sauce"	: 	"チリソース",
"Salt"	: 	"ソルト",
"Pepper"	: 	"ペッパー",
"Yogurt"	: 	"ヨーグルト",
"Whipped Cream"	: 	"ホイップクリーム",
"Cream Cheese"	: 	"クリームチーズ",
"Jam"	: 	"ベリージャム",
"Marmalade"	: 	"マーマレード",
"Olive Oil"	: 	"オリーブオイル",
"Vinegar"	: 	"ビネガー",
"Sweet Herba Mystica"	: 	"ひでん：あまスパイス",
"Salty Herba Mystica"	: 	"ひでん：しおスパイス",
"Sour Herba Mystica"	: 	"ひでん：すぱスパイス",
"Bitter Herba Mystica"	: 	"ひでん：にがスパイス",
"Spicy Herba Mystica"	: 	"ひでん：からスパイス",
"Lettuce"	: 	"レタス",
"Tomato"	: 	"トマトスライス",
"Cherry Tomatoes"	: 	"カットミニトマト",
"Cucumber"	: 	"キュウリスライス",
"Pickle"	: 	"ピクルススライス",
"Onion"	: 	"たまねぎスライス",
"Red Onion"	: 	"アーリーレッド",
"Green Bell Pepper"	: 	"ピーマンスライス",
"Red Bell Pepper"	: 	"あかパプリカスライス",
"Yellow Bell Pepper"	: 	"きパプリカスライス",
"Avocado"	: 	"アボカド",
"Bacon"	: 	"やきベーコン",
"Ham"	: 	"ハムスライス",
"Prosciutto"	: 	"なまハム",
"Chorizo"	: 	"やきチョリソー",
"Herbed Sausage"	: 	"ハーブソーセージ",
"Hamburger"	: 	"ハンバーグ",
"Klawf Stick"	: 	"ガケガニスティック",
"Smoked Fillet"	: 	"スモークきりみ",
"Fried Fillet"	: 	"きりみフライ",
"Egg"	: 	"スライスエッグ",
"Potato Tortilla"	: 	"トルティージャ",
"Tofu"	: 	"トーフ",
"Rice"	: 	"ライス",
"Noodles"	: 	"ヌードル",
"Potato Salad"	: 	"ポテトサラダ",
"Cheese"	: 	"スライスチーズ",
"Banana"	: 	"バナナスライス",
"Strawberry"	: 	"いちごスライス",
"Apple"	: 	"わぎりリンゴ",
"Kiwi"	: 	"わぎりキウイ",
"Pineapple"	: 	"カットパイン",
"Jalapeño"	: 	"ハラペーニョ",
"Horseradish"	: 	"ホースラディッシュ",
"Curry Powder"	: 	"カレーパウダー",
"Wasabi"	: 	"ワサビソース",
"Watercress"	: 	"クレソン",
"Basil"	: 	"バジル",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
"Venonat Fang"	: 	"コンパンのキバ",
"Diglett Dirt"	: 	"ディグダのつち",
"Meowth Fur"	: 	"ニャースのけ",
"Psyduck Down"	: 	"コダックのうもう",
"Mankey Fur"	: 	"マンキーのけ",
"Growlithe Fur"	: 	"ガーディのけ",
"Slowpoke Claw"	: 	"ヤドンのツメ",
"Magnemite Screw"	: 	"コイルのねじ",
"Grimer Toxin"	: 	"ベトベターのどくそ",
"Shellder Pearl"	: 	"シェルダーのしんじゅ",
"Gastly Gas"	: 	"ゴースのガス",
"Drowzee Fur"	: 	"スリープのけ",
"Voltorb Sparks"	: 	"ビリリダマのでんき",
"Scyther Claw"	: 	"ストライクのツメ",
"Tauros Hair"	: 	"ケンタロスのけ",
"Magikarp Scales"	: 	"コイキングのウロコ",
"Ditto Goo"	: 	"メタモンのべたべた",
"Eevee Fur"	: 	"イーブイのけ",
"Dratini Scales"	: 	"ミニリュウのウロコ",
"Pichu Fur"	: 	"ピチューのけ",
"Igglybuff Fluff"	: 	"ププリンのけ",
"Mareep Wool"	: 	"メリープのけだま",
"Hoppip Leaf"	: 	"ハネッコのはっぱ",
"Sunkern Leaf"	: 	"ヒマナッツのはっぱ",
"Murkrow Bauble"	: 	"ヤミカラスのおたから",
"Misdreavus Tears"	: 	"ムウマのなみだ",
"Girafarig Fur"	: 	"キリンリキのけ",
"Pineco Husk"	: 	"クヌギダマのから",
"Dunsparce Scales"	: 	"ノコッチのウロコ",
"Qwilfish Spines"	: 	"ハリーセンのトゲ",
"Heracross Claw"	: 	"ヘラクロスのツメ",
"Sneasel Claw"	: 	"ニューラのツメ",
"Teddiursa Claw"	: 	"ヒメグマのツメ",
"Delibird Parcel"	: 	"デリバードのにもつ",
"Houndour Fang"	: 	"デルビルのキバ",
"Phanpy Nail"	: 	"ゴマゾウのツメ",
"Stantler Hair"	: 	"オドシシのけ",
"Larvitar Claw"	: 	"ヨーギラスのツメ",
"Wingull Feather"	: 	"キャモメのはね",
"Ralts Dust"	: 	"ラルトスのおとしもの",
"Surskit Syrup"	: 	"アメタマのミツ",
"Shroomish Spores"	: 	"キノココのほうし",
"Slakoth Fur"	: 	"ナマケロのけ",
"Makuhita Sweat"	: 	"マクノシタのあせ",
"Azurill Fur"	: 	"ルリリのけ",
"Sableye Gem"	: 	"ヤミラミのほうせき",
"Meditite Sweat"	: 	"アサナンのあせ",
"Gulpin Mucus"	: 	"ゴクリンのねんえき",
"Numel Lava"	: 	"ドンメルのようがん",
"Torkoal Coal"	: 	"コータスのせきたん",
"Spoink Pearl"	: 	"バネブーのしんじゅ",
"Cacnea Needle"	: 	"サボネアのトゲ",
"Swablu Fluff"	: 	"チルットのはね",
"Zangoose Claw"	: 	"ザングースのツメ",
"Seviper Fang"	: 	"ハブネークのキバ",
"Barboach Slime"	: 	"ドジョッチのねんえき",
"Shuppet Scrap"	: 	"カゲボウズのきれはし",
"Tropius Leaf"	: 	"トロピウスのはっぱ",
"Snorunt Fur"	: 	"ユキワラシのけ",
"Luvdisc Scales"	: 	"ラブカスのウロコ",
"Bagon Scales"	: 	"タツベイのウロコ",
"Starly Feather"	: 	"ムックルのはね",
"Kricketot Shell"	: 	"コロボーシのぬけがら",
"Shinx Fang"	: 	"コリンクのキバ",
"Combee Honey"	: 	"ミツハニーのミツ",
"Pachirisu Fur"	: 	"パチリスのけ",
"Buizel Fur"	: 	"ブイゼルのけ",
"Shellos Mucus"	: 	"カラナクシのねんえき",
"Drifloon Gas"	: 	"フワンテのガス",
"Stunky Fur"	: 	"スカンプーのけ",
"Bronzor Fragment"	: 	"ドーミラーのかけら",
"Bonsly Tears"	: 	"ウソハチのなみだ",
"Happiny Dust"	: 	"ピンプクのおとしもの",
"Spiritomb Fragment"	: 	"ミカルゲのかけら",
"Gible Scales"	: 	"フカマルのウロコ",
"Riolu Fur"	: 	"リオルのけ",
"Hippopotas Sand"	: 	"ヒポポタスのすな",
"Croagunk Poison"	: 	"グレッグルのどくそ",
"Finneon Scales"	: 	"ケイコウオのウロコ",
"Snover Berries"	: 	"ユキカブリのみ",
"Rotom Sparks"	: 	"ロトムのでんき",
"Petilil Leaf"	: 	"チュリネのはっぱ",
"Basculin Fang"	: 	"バスラオのキバ",
"Sandile Claw"	: 	"メグロコのツメ",
"Zorua Fur"	: 	"ゾロアのけ",
"Gothita Eyelash"	: 	"ゴチムのまつげ",
"Deerling Hair"	: 	"シキジカのけ",
"Foongus Spores"	: 	"タマゲタケのほうし",
"Alomomola Mucus"	: 	"ママンボウのねんえき",
"Tynamo Slime"	: 	"シビシラスのねんえき",
"Axew Scales"	: 	"キバゴのウロコ",
"Cubchoo Fur"	: 	"クマシュンのけ",
"Cryogonal Ice"	: 	"フリージオのこおり",
"Pawniard Blade"	: 	"コマタナのやいば",
"Rufflet Feather"	: 	"ワシボンのはね",
"Deino Scales"	: 	"モノズのウロコ",
"Larvesta Fuzz"	: 	"メラルバのけ",
"Fletchling Feather"	: 	"ヤヤコマのはね",
"Scatterbug Powder"	: 	"コフキムシのこな",
"Litleo Tuft"	: 	"シシコのたてがみ",
"Flabébé Pollen"	: 	"フラベベのかふん",
"Skiddo Leaf"	: 	"メェークルのはっぱ",
"Skrelp Kelp"	: 	"クズモーのもくず",
"Clauncher Claw"	: 	"ウデッポウのハサミ",
"Hawlucha Down"	: 	"ルチャブルのうもう",
"Dedenne Fur"	: 	"デデンネのけ",
"Goomy Goo"	: 	"ヌメラのねんえき",
"Klefki Key"	: 	"クレッフィのかぎ",
"Bergmite Ice"	: 	"カチコールのこおり",
"Noibat Fur"	: 	"オンバットのけ",
"Yungoos Fur"	: 	"ヤングースのけ",
"Crabrawler Shell"	: 	"マケンカニのから",
"Oricorio Feather"	: 	"オドリドリのはね",
"Rockruff Rock"	: 	"イワンコのいわ",
"Mareanie Spike"	: 	"ヒドイデのトゲ",
"Mudbray Mud"	: 	"ドロバンコのどろ",
"Fomantis Leaf"	: 	"カリキリのはっぱ",
"Salandit Gas"	: 	"ヤトウモリのガス",
"Bounsweet Sweat"	: 	"アマカジのあせ",
"Oranguru Fur"	: 	"ヤレユータンのけ",
"Passimian Fur"	: 	"ナゲツケサルのけ",
"Sandygast Sand"	: 	"スナバァのすな",
"Komala Claw"	: 	"ネッコアラのツメ",
"Mimikyu Scrap"	: 	"ミミッキュのきれはし",
"Bruxish Tooth"	: 	"ハギギシリのは",
"Chewtle Claw"	: 	"カムカメのツメ",
"Skwovet Fur"	: 	"ホシガリスのけ",
"Arrokuda Scales"	: 	"サシカマスのウロコ",
"Rookidee Feather"	: 	"ココガラのはね",
"Toxel Sparks"	: 	"エレズンのでんき",
"Falinks Sweat"	: 	"タイレーツのあせ",
"Cufant Tarnish"	: 	"ゾウドウのさび",
"Rolycoly Coal"	: 	"タンドンのせきたん",
"Silicobra Sand"	: 	"スナヘビのすな",
"Indeedee Fur"	: 	"イエッサンのけ",
"Pincurchin Spines"	: 	"バチンウニのはり",
"Snom Thread"	: 	"ユキハミのいと",
"Impidimp Hair"	: 	"ベロバーのけ",
"Applin Juice"	: 	"カジッチュのかじゅう",
"Sinistea Chip"	: 	"ヤバチャのかけら",
"Hatenna Dust"	: 	"ミブリムのおとしもの",
"Stonjourner Stone"	: 	"イシヘンジンのいわ",
"Eiscue Down"	: 	"コオリッポのうもう",
"Dreepy Powder"	: 	"ドラメシヤのこな",
""	: 	"",
""	: 	"",
""	: 	"",
"Lechonk Hair"	: 	"グルトンのけ",
"Tarountula Thread"	: 	"タマンチュラのいと",
"Nymble Claw"	: 	"マメバッタのツメ",
"Rellor Mud"	: 	"シガロコのどろ",
"Greavard Wax"	: 	"ボチのろう",
"Flittle Down"	: 	"ヒラヒナのうもう",
"Wiglett Sand"	: 	"ウミディグダのすな",
"Dondozo Whisker"	: 	"ヘイラッシャのヒゲ",
"Veluza Fillet"	: 	"ミガルーサのきりみ",
"Finizen Mucus"	: 	"ナミイルカのねんえき",
"Smoliv Oil"	: 	"ミニーブのオイル",
"Capsakid Seed"	: 	"カプサイジのたね",
"Tadbulb Mucus"	: 	"ズピカのねんえき",
"Varoom Fume"	: 	"ブロロンのガス",
"Orthworm Tarnish"	: 	"ミミズズのさび",
"Tandemaus Fur"	: 	"ワッカネズミのけ",
"Cetoddle Grease"	: 	"アルクジラのあぶら",
"Frigibax Scales"	: 	"セビエのウロコ",
"Tatsugiri Scales"	: 	"シャリタツのウロコ",
"Cyclizar Scales"	: 	"モトトカゲのウロコ",
"Pawmi Fur"	: 	"パモのけ",
""	: 	"",
""	: 	"",
"Wattrel Feather"	: 	"カイデンのはね",
"Bombirdier Feather"	: 	"オトシドリのはね",
"Squawkabilly Feather"	: 	"イキリンコのはね",
"Flamigo Down"	: 	"カラミンゴのうもう",
"Klawf Claw"	: 	"ガケガニのハサミ",
"Nacli Salt"	: 	"コジオのしお",
"Glimmet Crystal"	: 	"キラーメのけっしょう",
"Shroodle Ink"	: 	"シルシュルーのインク",
"Fidough Fur"	: 	"パピモッチのけ",
"Maschiff Fang"	: 	"オラチフのキバ",
"Bramblin Twig"	: 	"アノクサのえだ",
"Gimmighoul Coin"	: 	"コレクレーのコイン",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
"Tinkatink Hair"	: 	"カヌチャンのけ",
"Charcadet Soot"	: 	"カルボウのすす",
"Toedscool Flaps"	: 	"ノノクラゲのヒラヒラ",
"Wooper Slime"	: 	"ウパーのねんえき",
"TM100"	: 	"わざマシン１００",
"TM101"	: 	"わざマシン１０１",
"TM102"	: 	"わざマシン１０２",
"TM103"	: 	"わざマシン１０３",
"TM104"	: 	"わざマシン１０４",
"TM105"	: 	"わざマシン１０５",
"TM106"	: 	"わざマシン１０６",
"TM107"	: 	"わざマシン１０７",
"TM108"	: 	"わざマシン１０８",
"TM109"	: 	"わざマシン１０９",
"TM110"	: 	"わざマシン１１０",
"TM111"	: 	"わざマシン１１１",
"TM112"	: 	"わざマシン１１２",
"TM113"	: 	"わざマシン１１３",
"TM114"	: 	"わざマシン１１４",
"TM115"	: 	"わざマシン１１５",
"TM116"	: 	"わざマシン１１６",
"TM117"	: 	"わざマシン１１７",
"TM118"	: 	"わざマシン１１８",
"TM119"	: 	"わざマシン１１９",
"TM120"	: 	"わざマシン１２０",
"TM121"	: 	"わざマシン１２１",
"TM122"	: 	"わざマシン１２２",
"TM123"	: 	"わざマシン１２３",
"TM124"	: 	"わざマシン１２４",
"TM125"	: 	"わざマシン１２５",
"TM126"	: 	"わざマシン１２６",
"TM127"	: 	"わざマシン１２７",
"TM128"	: 	"わざマシン１２８",
"TM129"	: 	"わざマシン１２９",
"TM130"	: 	"わざマシン１３０",
"TM131"	: 	"わざマシン１３１",
"TM132"	: 	"わざマシン１３２",
"TM133"	: 	"わざマシン１３３",
"TM134"	: 	"わざマシン１３４",
"TM135"	: 	"わざマシン１３５",
"TM136"	: 	"わざマシン１３６",
"TM137"	: 	"わざマシン１３７",
"TM138"	: 	"わざマシン１３８",
"TM139"	: 	"わざマシン１３９",
"TM140"	: 	"わざマシン１４０",
"TM141"	: 	"わざマシン１４１",
"TM142"	: 	"わざマシン１４２",
"TM143"	: 	"わざマシン１４３",
"TM144"	: 	"わざマシン１４４",
"TM145"	: 	"わざマシン１４５",
"TM146"	: 	"わざマシン１４６",
"TM147"	: 	"わざマシン１４７",
"TM148"	: 	"わざマシン１４８",
"TM149"	: 	"わざマシン１４９",
"TM150"	: 	"わざマシン１５０",
"TM151"	: 	"わざマシン１５１",
"TM152"	: 	"わざマシン１５２",
"TM153"	: 	"わざマシン１５３",
"TM154"	: 	"わざマシン１５４",
"TM155"	: 	"わざマシン１５５",
"TM156"	: 	"わざマシン１５６",
"TM157"	: 	"わざマシン１５７",
"TM158"	: 	"わざマシン１５８",
"TM159"	: 	"わざマシン１５９",
"TM160"	: 	"わざマシン１６０",
"TM161"	: 	"わざマシン１６１",
"TM162"	: 	"わざマシン１６２",
"TM163"	: 	"わざマシン１６３",
"TM164"	: 	"わざマシン１６４",
"TM165"	: 	"わざマシン１６５",
"TM166"	: 	"わざマシン１６６",
"TM167"	: 	"わざマシン１６７",
"TM168"	: 	"わざマシン１６８",
"TM169"	: 	"わざマシン１６９",
"TM170"	: 	"わざマシン１７０",
"TM171"	: 	"わざマシン１７１",
"TM172"	: 	"わざマシン１７２",
"TM173"	: 	"わざマシン１７３",
"TM174"	: 	"わざマシン１７４",
"TM175"	: 	"わざマシン１７５",
"TM176"	: 	"わざマシン１７６",
"TM177"	: 	"わざマシン１７７",
"TM178"	: 	"わざマシン１７８",
"TM179"	: 	"わざマシン１７９",
"TM180"	: 	"わざマシン１８０",
"TM181"	: 	"わざマシン１８１",
"TM182"	: 	"わざマシン１８２",
"TM183"	: 	"わざマシン１８３",
"TM184"	: 	"わざマシン１８４",
"TM185"	: 	"わざマシン１８５",
"TM186"	: 	"わざマシン１８６",
"TM187"	: 	"わざマシン１８７",
"TM188"	: 	"わざマシン１８８",
"TM189"	: 	"わざマシン１８９",
"TM190"	: 	"わざマシン１９０",
"TM191"	: 	"わざマシン１９１",
"TM192"	: 	"わざマシン１９２",
"TM193"	: 	"わざマシン１９３",
"TM194"	: 	"わざマシン１９４",
"TM195"	: 	"わざマシン１９５",
"TM196"	: 	"わざマシン１９６",
"TM197"	: 	"わざマシン１９７",
"TM198"	: 	"わざマシン１９８",
"TM199"	: 	"わざマシン１９９",
"TM200"	: 	"わざマシン２００",
"TM201"	: 	"わざマシン２０１",
"TM202"	: 	"わざマシン２０２",
"TM203"	: 	"わざマシン２０３",
"TM204"	: 	"わざマシン２０４",
"TM205"	: 	"わざマシン２０５",
"TM206"	: 	"わざマシン２０６",
"TM207"	: 	"わざマシン２０７",
"TM208"	: 	"わざマシン２０８",
"TM209"	: 	"わざマシン２０９",
"TM210"	: 	"わざマシン２１０",
"TM211"	: 	"わざマシン２１１",
"TM212"	: 	"わざマシン２１２",
"TM213"	: 	"わざマシン２１３",
"TM214"	: 	"わざマシン２１４",
"TM215"	: 	"わざマシン２１５",
"TM216"	: 	"わざマシン２１６",
"TM217"	: 	"わざマシン２１７",
"TM218"	: 	"わざマシン２１８",
"TM219"	: 	"わざマシン２１９",
"TM220"	: 	"わざマシン２２０",
"TM221"	: 	"わざマシン２２１",
"TM222"	: 	"わざマシン２２２",
"TM223"	: 	"わざマシン２２３",
"TM224"	: 	"わざマシン２２４",
"TM225"	: 	"わざマシン２２５",
"TM226"	: 	"わざマシン２２６",
"TM227"	: 	"わざマシン２２７",
"TM228"	: 	"わざマシン２２８",
"TM229"	: 	"わざマシン２２９",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
""	: 	"",
"Picnic Set"	: 	"ピクニックセット",
""	: 	"",
"Academy Bottle"	: 	"スクールボトル",
"Academy Bottle"	: 	"スクールボトル",
"Polka-Dot Bottle"	: 	"みずたまボトル",
"Striped Bottle"	: 	"ストライプボトル",
"Diamond Bottle"	: 	"ダイヤボトル",
"Academy Cup"	: 	"スクールカップ",
"Academy Cup"	: 	"スクールカップ",
"Striped Cup"	: 	"たてストライプカップ",
"Polka-Dot Cup"	: 	"みずたまカップ",
"Flower Pattern Cup"	: 	"フラワーカップ",
"Academy Tablecloth"	: 	"スクールクロス",
"Academy Tablecloth"	: 	"スクールクロス",
"Whimsical Tablecloth"	: 	"ファンシークロス",
"Leafy Tablecloth"	: 	"ネイチャークロス",
"Spooky Tablecloth"	: 	"うらめしクロス",
""	: 	"",
"Academy Ball"	: 	"スクールボール",
"Academy Ball"	: 	"スクールボール",
"Marill Ball"	: 	"マリルボール",
"Yarn Ball"	: 	"けいとボール",
"Cyber Ball"	: 	"ゲーミングボール",
"Gold Pick"	: 	"ゴールドピック",
"Silver Pick"	: 	"シルバーピック",
"Red-Flag Pick"	: 	"あかいはたピック",
"Blue-Flag Pick"	: 	"あおいはたピック",
"Pika-Pika Pick"	: 	"ピカピカピック",
"Winking Pika Pick"	: 	"パチピカピック",
"Vee-Vee Pick"	: 	"ブイブイピック",
"Smiling Vee Pick"	: 	"ニコブイピック",
"Blue Poké Ball Pick"	: 	"あおボールピック",
""	: 	"",
"Auspicious Armor"	: 	"イワイノヨロイ",
"Leader’s Crest"	: 	"かしらのしるし",
""	: 	"",
""	: 	"",
"Pink Bottle"	: 	"ピンクボトル",
"Blue Bottle"	: 	"ブルーボトル",
"Yellow Bottle"	: 	"イエローボトル",
"Steel Bottle (R)"	: 	"Rステンレスボトル",
"Steel Bottle (Y)"	: 	"Yステンレスボトル",
"Steel Bottle (B)"	: 	"Bステンレスボトル",
"Silver Bottle"	: 	"シルバーチタンボトル",
"Barred Cup"	: 	"よこストライプカップ",
"Diamond Pattern Cup"	: 	"ダイヤカップ",
"Fire Pattern Cup"	: 	"ファイヤーカップ",
"Pink Cup"	: 	"ピンクカップ",
"Blue Cup"	: 	"ブルーカップ",
"Yellow Cup"	: 	"イエローカップ",
"Pikachu Cup"	: 	"ピカチュウカップ",
"Eevee Cup"	: 	"イーブイカップ",
"Slowpoke Cup"	: 	"ヤドンカップ",
"Silver Cup"	: 	"シルバーチタンカップ",
"Exercise Ball"	: 	"バランスボール",
"Plaid Tablecloth (Y)"	: 	"きいろチェッククロス",
"Plaid Tablecloth (B)"	: 	"あおチェッククロス",
"Plaid Tablecloth (R)"	: 	"あかチェッククロス",
"B&W Grass Tablecloth"	: 	"くさむらモノクロス",
"Battle Tablecloth"	: 	"しょうぶクロス",
"Monstrous Tablecloth"	: 	"かいじゅうクロス",
"Striped Tablecloth"	: 	"ストライプクロス",
"Diamond Tablecloth"	: 	"ダイヤクロス",
"Polka-Dot Tablecloth"	: 	"みずたまクロス",
"Lilac Tablecloth"	: 	"パープルクロス",
"Mint Tablecloth"	: 	"ミントクロス",
"Peach Tablecloth"	: 	"ベージュクロス",
"Yellow Tablecloth"	: 	"イエロークロス",
"Blue Tablecloth"	: 	"ブルークロス",
"Pink Tablecloth"	: 	"ピンククロス",
"Gold Bottle"	: 	"ゴールドチタンボトル",
"Bronze Bottle"	: 	"ブロンズチタンボトル",
"Gold Cup"	: 	"ゴールドチタンカップ",
"Bronze Cup"	: 	"ブロンズチタンカップ",
"Green Poké Ball Pick"	: 	"みどりボールピック",
"Red Poké Ball Pick"	: 	"あかボールピック",
"Party Sparkler Pick"	: 	"おいわいはなびピック",
"Heroic Sword Pick"	: 	"ゆうしゃのけんピック",
"Magical Star Pick"	: 	"マジカルスターピック",
"Magical Heart Pick"	: 	"マジカルハートピック",
"Parasol Pick"	: 	"パラソルピック",
"Blue-Sky Flower Pick"	: 	"あおぞらおはなピック",
"Sunset Flower Pick"	: 	"ゆうやけおはなピック",
"Sunrise Flower Pick"	: 	"あさやけおはなピック",
"Blue Dish"	: 	"ブループレート",
"Green Dish"	: 	"グリーンプレート",
"Orange Dish"	: 	"オレンジプレート",
"Red Dish"	: 	"レッドプレート",
"White Dish"	: 	"ホワイトプレート",
"Yellow Dish"	: 	"イエロープレート",
"Fairy Feather"	: 	"ようせいのハネ",
"Syrupy Apple"	: 	"みついりりんご",
"Unremarkable Teacup"	: 	"ボンサクのちゃわん",
"Masterpiece Teacup"	: 	"ケッサクのちゃわん",
"Teal Mask"	: 	"みどりのめん",
"Cornerstone Mask"	: 	"いしずえのめん",
"Wellspring Mask"	: 	"いどのめん",
"Hearthflame Mask"	: 	"かまどのめん",
"Teal Style Card"	: 	"おしゃれカードみどり",
"Crystal Cluster"	: 	"けっしょうのかけら",
"Health Mochi"	: 	"たいりょくのもち",
"Muscle Mochi"	: 	"きんりょくのもち",
"Resist Mochi"	: 	"ていこうのもち",
"Genius Mochi"	: 	"ちりょくのもち",
"Clever Mochi"	: 	"せいしんのもち",
"Swift Mochi"	: 	"しゅんぱつのもち",
"Simple Chairs"	: 	"シンプルチェア",
"Academy Chairs"	: 	"スクールチェア",
"Academy Chairs"	: 	"スクールチェア",
"Whimsical Chairs"	: 	"ファンシーチェア",
"Leafy Chairs"	: 	"ネイチャーチェア",
"Spooky Chairs"	: 	"うらめしチェア",
"Plaid Chairs (Y)"	: 	"きいろチェックチェア",
"Plaid Chairs (B)"	: 	"あおチェックチェア",
"Plaid Chairs (R)"	: 	"あかチェックチェア",
"B&W Grass Chairs"	: 	"くさむらチェア",
"Battle Chairs"	: 	"しょうぶチェア",
"Monstrous Chairs"	: 	"かいじゅうチェア",
"Striped Chairs"	: 	"ストライプチェア",
"Diamond Chairs"	: 	"ダイヤチェア",
"Polka-Dot Chairs"	: 	"みずたまチェア",
"Lilac Chairs"	: 	"パープルチェア",
"Mint Chairs"	: 	"ミントチェア",
"Peach Chairs"	: 	"ベージュチェア",
"Yellow Chairs"	: 	"イエローチェア",
"Blue Chairs"	: 	"ブルーチェア",
"Pink Chairs"	: 	"ピンクチェア",
"Ekans Fang"	: 	"アーボのキバ",
"Sandshrew Claw"	: 	"サンドのツメ",
"Cleffa Fur"	: 	"ピィのけ",
"Vulpix Fur"	: 	"ロコンのけ",
"Poliwag Slime"	: 	"ニョロモのねんえき",
"Bellsprout Vine"	: 	"マダツボミのツル",
"Geodude Fragment"	: 	"イシツブテのかけら",
"Koffing Gas"	: 	"ドガースのガス",
"Munchlax Fang"	: 	"ゴンベのキバ",
"Sentret Fur"	: 	"オタチのけ",
"Hoothoot Feather"	: 	"ホーホーのはね",
"Spinarak Thread"	: 	"イトマルのいと",
"Aipom Hair"	: 	"エイパムのけ",
"Yanma Spike"	: 	"ヤンヤンマのトゲ",
"Gligar Fang"	: 	"グライガーのキバ",
"Slugma Lava"	: 	"マグマッグのようがん",
"Swinub Hair"	: 	"ウリムーのけ",
"Poochyena Fang"	: 	"ポチエナのキバ",
"Lotad Leaf"	: 	"ハスボーのはっぱ",
"Seedot Stem"	: 	"タネボーのえだ",
"Nosepass Fragment"	: 	"ノズパスのかけら",
"Volbeat Fluid"	: 	"バルビートのしる",
"Illumise Fluid"	: 	"イルミーゼのしる",
"Corphish Shell"	: 	"ヘイガニのから",
"Feebas Scales"	: 	"ヒンバスのうろこ",
"Duskull Fragment"	: 	"ヨマワルのかけら",
"Chingling Fragment"	: 	"リーシャンのかけら",
"Timburr Sweat"	: 	"ドッコラーのあせ",
"Sewaddle Leaf"	: 	"クルミルのはっぱ",
"Ducklett Feather"	: 	"コアルヒーのはね",
"Litwick Soot"	: 	"ヒトモシのすす",
"Mienfoo Claw"	: 	"コジョフーのツメ",
"Vullaby Feather"	: 	"バルチャイのはね",
"Carbink Jewel"	: 	"メレシーのほうせき",
"Phantump Twig"	: 	"ボクレーのえだ",
"Grubbin Thread"	: 	"アゴジムシのいと",
"Cutiefly Powder"	: 	"アブリーのこな",
"Jangmo-o Scales"	: 	"ジャラコのウロコ",
"Cramorant Down"	: 	"ウッウのうもう",
"Morpeko Snack"	: 	"モルペコのたね",
"Poltchageist Powder"	: 	"チャデスのこな",
"Fresh-Start Mochi"	: 	"まっさらもち",
"Roto-Stick"	: 	"ロトりぼう",
"Glimmering Charm"	: 	"きらめくおまもり",
}		